/**
 * BloodBridge Inventory & Demand Forecasting Engine — Targeted WhatsApp/SMS Urgent Blood Shortage Mobilization
 * Predictive modeling, seasonal shock simulation, and wastage minimization.
 */

export interface RecallCampaignRecord {
  forecastId: string;
  targetBloodGroup: 'A+' | 'A-' | 'B+' | 'B-' | 'AB+' | 'AB-' | 'O+' | 'O-';
  componentType: 'PRBC' | 'FFP' | 'PLATELETS' | 'CRYOPRECIPITATE' | 'WHOLE_BLOOD';
  historicalDailyConsumptionUnits: number;
  predictedWeeklyDemandUnits: number;
  safetyBufferRequiredUnits: number;
  currentInventoryUnits: number;
  netSurplusOrDeficitUnits: number;
  forecastConfidenceIntervalPercentage: number;
  seasonalSurgeFactor: number;
  riskOfStockoutPercentage: number;
  recommendedEmergencyDonorCallCount: number;
  computedTimestampIso: string;
}

export const SMSWHATSAPPDONORRECALLCAMPAIGN_FORECAST_DATA: RecallCampaignRecord[] = [
  {
    forecastId: 'FCST-SMSW-0001',
    targetBloodGroup: 'A-',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 16,
    predictedWeeklyDemandUnits: 55,
    safetyBufferRequiredUnits: 21,
    currentInventoryUnits: 50,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 93.3,
    seasonalSurgeFactor: 1.10,
    riskOfStockoutPercentage: 46,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0002',
    targetBloodGroup: 'B+',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 17,
    predictedWeeklyDemandUnits: 60,
    safetyBufferRequiredUnits: 22,
    currentInventoryUnits: 55,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 94.1,
    seasonalSurgeFactor: 1.15,
    riskOfStockoutPercentage: 47,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0003',
    targetBloodGroup: 'B-',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 18,
    predictedWeeklyDemandUnits: 65,
    safetyBufferRequiredUnits: 23,
    currentInventoryUnits: 60,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 94.9,
    seasonalSurgeFactor: 1.20,
    riskOfStockoutPercentage: 48,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0004',
    targetBloodGroup: 'AB+',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 19,
    predictedWeeklyDemandUnits: 70,
    safetyBufferRequiredUnits: 24,
    currentInventoryUnits: 65,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 95.7,
    seasonalSurgeFactor: 1.25,
    riskOfStockoutPercentage: 49,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0005',
    targetBloodGroup: 'AB-',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 20,
    predictedWeeklyDemandUnits: 75,
    safetyBufferRequiredUnits: 25,
    currentInventoryUnits: 70,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 96.5,
    seasonalSurgeFactor: 1.30,
    riskOfStockoutPercentage: 50,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0006',
    targetBloodGroup: 'O+',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 21,
    predictedWeeklyDemandUnits: 80,
    safetyBufferRequiredUnits: 26,
    currentInventoryUnits: 75,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 92.5,
    seasonalSurgeFactor: 1.35,
    riskOfStockoutPercentage: 51,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0007',
    targetBloodGroup: 'O-',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 22,
    predictedWeeklyDemandUnits: 85,
    safetyBufferRequiredUnits: 27,
    currentInventoryUnits: 80,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 93.3,
    seasonalSurgeFactor: 1.40,
    riskOfStockoutPercentage: 52,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0008',
    targetBloodGroup: 'A+',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 23,
    predictedWeeklyDemandUnits: 90,
    safetyBufferRequiredUnits: 28,
    currentInventoryUnits: 85,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 94.1,
    seasonalSurgeFactor: 1.05,
    riskOfStockoutPercentage: 53,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0009',
    targetBloodGroup: 'A-',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 24,
    predictedWeeklyDemandUnits: 95,
    safetyBufferRequiredUnits: 29,
    currentInventoryUnits: 90,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 94.9,
    seasonalSurgeFactor: 1.10,
    riskOfStockoutPercentage: 54,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0010',
    targetBloodGroup: 'B+',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 25,
    predictedWeeklyDemandUnits: 100,
    safetyBufferRequiredUnits: 20,
    currentInventoryUnits: 95,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 95.7,
    seasonalSurgeFactor: 1.15,
    riskOfStockoutPercentage: 55,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0011',
    targetBloodGroup: 'B-',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 26,
    predictedWeeklyDemandUnits: 105,
    safetyBufferRequiredUnits: 21,
    currentInventoryUnits: 100,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 96.5,
    seasonalSurgeFactor: 1.20,
    riskOfStockoutPercentage: 56,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0012',
    targetBloodGroup: 'AB+',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 15,
    predictedWeeklyDemandUnits: 110,
    safetyBufferRequiredUnits: 22,
    currentInventoryUnits: 105,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 92.5,
    seasonalSurgeFactor: 1.25,
    riskOfStockoutPercentage: 57,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0013',
    targetBloodGroup: 'AB-',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 16,
    predictedWeeklyDemandUnits: 115,
    safetyBufferRequiredUnits: 23,
    currentInventoryUnits: 110,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 93.3,
    seasonalSurgeFactor: 1.30,
    riskOfStockoutPercentage: 58,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0014',
    targetBloodGroup: 'O+',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 17,
    predictedWeeklyDemandUnits: 120,
    safetyBufferRequiredUnits: 24,
    currentInventoryUnits: 115,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 94.1,
    seasonalSurgeFactor: 1.35,
    riskOfStockoutPercentage: 59,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0015',
    targetBloodGroup: 'O-',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 18,
    predictedWeeklyDemandUnits: 125,
    safetyBufferRequiredUnits: 25,
    currentInventoryUnits: 120,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 94.9,
    seasonalSurgeFactor: 1.40,
    riskOfStockoutPercentage: 60,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0016',
    targetBloodGroup: 'A+',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 19,
    predictedWeeklyDemandUnits: 130,
    safetyBufferRequiredUnits: 26,
    currentInventoryUnits: 125,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 95.7,
    seasonalSurgeFactor: 1.05,
    riskOfStockoutPercentage: 61,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0017',
    targetBloodGroup: 'A-',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 20,
    predictedWeeklyDemandUnits: 135,
    safetyBufferRequiredUnits: 27,
    currentInventoryUnits: 130,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 96.5,
    seasonalSurgeFactor: 1.10,
    riskOfStockoutPercentage: 62,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0018',
    targetBloodGroup: 'B+',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 21,
    predictedWeeklyDemandUnits: 140,
    safetyBufferRequiredUnits: 28,
    currentInventoryUnits: 135,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 92.5,
    seasonalSurgeFactor: 1.15,
    riskOfStockoutPercentage: 63,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0019',
    targetBloodGroup: 'B-',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 22,
    predictedWeeklyDemandUnits: 145,
    safetyBufferRequiredUnits: 29,
    currentInventoryUnits: 140,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 93.3,
    seasonalSurgeFactor: 1.20,
    riskOfStockoutPercentage: 64,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0020',
    targetBloodGroup: 'AB+',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 23,
    predictedWeeklyDemandUnits: 150,
    safetyBufferRequiredUnits: 20,
    currentInventoryUnits: 145,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 94.1,
    seasonalSurgeFactor: 1.25,
    riskOfStockoutPercentage: 65,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0021',
    targetBloodGroup: 'AB-',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 24,
    predictedWeeklyDemandUnits: 155,
    safetyBufferRequiredUnits: 21,
    currentInventoryUnits: 150,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 94.9,
    seasonalSurgeFactor: 1.30,
    riskOfStockoutPercentage: 66,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0022',
    targetBloodGroup: 'O+',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 25,
    predictedWeeklyDemandUnits: 160,
    safetyBufferRequiredUnits: 22,
    currentInventoryUnits: 155,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 95.7,
    seasonalSurgeFactor: 1.35,
    riskOfStockoutPercentage: 67,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0023',
    targetBloodGroup: 'O-',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 26,
    predictedWeeklyDemandUnits: 165,
    safetyBufferRequiredUnits: 23,
    currentInventoryUnits: 160,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 96.5,
    seasonalSurgeFactor: 1.40,
    riskOfStockoutPercentage: 68,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0024',
    targetBloodGroup: 'A+',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 15,
    predictedWeeklyDemandUnits: 170,
    safetyBufferRequiredUnits: 24,
    currentInventoryUnits: 165,
    netSurplusOrDeficitUnits: -5,
    forecastConfidenceIntervalPercentage: 92.5,
    seasonalSurgeFactor: 1.05,
    riskOfStockoutPercentage: 69,
    recommendedEmergencyDonorCallCount: 15,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0025',
    targetBloodGroup: 'A-',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 16,
    predictedWeeklyDemandUnits: 175,
    safetyBufferRequiredUnits: 25,
    currentInventoryUnits: 45,
    netSurplusOrDeficitUnits: -130,
    forecastConfidenceIntervalPercentage: 93.3,
    seasonalSurgeFactor: 1.10,
    riskOfStockoutPercentage: 70,
    recommendedEmergencyDonorCallCount: 390,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0026',
    targetBloodGroup: 'B+',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 17,
    predictedWeeklyDemandUnits: 180,
    safetyBufferRequiredUnits: 26,
    currentInventoryUnits: 50,
    netSurplusOrDeficitUnits: -130,
    forecastConfidenceIntervalPercentage: 94.1,
    seasonalSurgeFactor: 1.15,
    riskOfStockoutPercentage: 71,
    recommendedEmergencyDonorCallCount: 390,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0027',
    targetBloodGroup: 'B-',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 18,
    predictedWeeklyDemandUnits: 185,
    safetyBufferRequiredUnits: 27,
    currentInventoryUnits: 55,
    netSurplusOrDeficitUnits: -130,
    forecastConfidenceIntervalPercentage: 94.9,
    seasonalSurgeFactor: 1.20,
    riskOfStockoutPercentage: 72,
    recommendedEmergencyDonorCallCount: 390,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0028',
    targetBloodGroup: 'AB+',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 19,
    predictedWeeklyDemandUnits: 190,
    safetyBufferRequiredUnits: 28,
    currentInventoryUnits: 60,
    netSurplusOrDeficitUnits: -130,
    forecastConfidenceIntervalPercentage: 95.7,
    seasonalSurgeFactor: 1.25,
    riskOfStockoutPercentage: 73,
    recommendedEmergencyDonorCallCount: 390,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0029',
    targetBloodGroup: 'AB-',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 20,
    predictedWeeklyDemandUnits: 195,
    safetyBufferRequiredUnits: 29,
    currentInventoryUnits: 65,
    netSurplusOrDeficitUnits: -130,
    forecastConfidenceIntervalPercentage: 96.5,
    seasonalSurgeFactor: 1.30,
    riskOfStockoutPercentage: 74,
    recommendedEmergencyDonorCallCount: 390,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0030',
    targetBloodGroup: 'O+',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 21,
    predictedWeeklyDemandUnits: 50,
    safetyBufferRequiredUnits: 20,
    currentInventoryUnits: 70,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 92.5,
    seasonalSurgeFactor: 1.35,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0031',
    targetBloodGroup: 'O-',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 22,
    predictedWeeklyDemandUnits: 55,
    safetyBufferRequiredUnits: 21,
    currentInventoryUnits: 75,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 93.3,
    seasonalSurgeFactor: 1.40,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0032',
    targetBloodGroup: 'A+',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 23,
    predictedWeeklyDemandUnits: 60,
    safetyBufferRequiredUnits: 22,
    currentInventoryUnits: 80,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 94.1,
    seasonalSurgeFactor: 1.05,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0033',
    targetBloodGroup: 'A-',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 24,
    predictedWeeklyDemandUnits: 65,
    safetyBufferRequiredUnits: 23,
    currentInventoryUnits: 85,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 94.9,
    seasonalSurgeFactor: 1.10,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0034',
    targetBloodGroup: 'B+',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 25,
    predictedWeeklyDemandUnits: 70,
    safetyBufferRequiredUnits: 24,
    currentInventoryUnits: 90,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 95.7,
    seasonalSurgeFactor: 1.15,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0035',
    targetBloodGroup: 'B-',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 26,
    predictedWeeklyDemandUnits: 75,
    safetyBufferRequiredUnits: 25,
    currentInventoryUnits: 95,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 96.5,
    seasonalSurgeFactor: 1.20,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0036',
    targetBloodGroup: 'AB+',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 15,
    predictedWeeklyDemandUnits: 80,
    safetyBufferRequiredUnits: 26,
    currentInventoryUnits: 100,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 92.5,
    seasonalSurgeFactor: 1.25,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0037',
    targetBloodGroup: 'AB-',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 16,
    predictedWeeklyDemandUnits: 85,
    safetyBufferRequiredUnits: 27,
    currentInventoryUnits: 105,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 93.3,
    seasonalSurgeFactor: 1.30,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0038',
    targetBloodGroup: 'O+',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 17,
    predictedWeeklyDemandUnits: 90,
    safetyBufferRequiredUnits: 28,
    currentInventoryUnits: 110,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 94.1,
    seasonalSurgeFactor: 1.35,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0039',
    targetBloodGroup: 'O-',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 18,
    predictedWeeklyDemandUnits: 95,
    safetyBufferRequiredUnits: 29,
    currentInventoryUnits: 115,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 94.9,
    seasonalSurgeFactor: 1.40,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0040',
    targetBloodGroup: 'A+',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 19,
    predictedWeeklyDemandUnits: 100,
    safetyBufferRequiredUnits: 20,
    currentInventoryUnits: 120,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 95.7,
    seasonalSurgeFactor: 1.05,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0041',
    targetBloodGroup: 'A-',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 20,
    predictedWeeklyDemandUnits: 105,
    safetyBufferRequiredUnits: 21,
    currentInventoryUnits: 125,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 96.5,
    seasonalSurgeFactor: 1.10,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0042',
    targetBloodGroup: 'B+',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 21,
    predictedWeeklyDemandUnits: 110,
    safetyBufferRequiredUnits: 22,
    currentInventoryUnits: 130,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 92.5,
    seasonalSurgeFactor: 1.15,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0043',
    targetBloodGroup: 'B-',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 22,
    predictedWeeklyDemandUnits: 115,
    safetyBufferRequiredUnits: 23,
    currentInventoryUnits: 135,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 93.3,
    seasonalSurgeFactor: 1.20,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0044',
    targetBloodGroup: 'AB+',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 23,
    predictedWeeklyDemandUnits: 120,
    safetyBufferRequiredUnits: 24,
    currentInventoryUnits: 140,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 94.1,
    seasonalSurgeFactor: 1.25,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0045',
    targetBloodGroup: 'AB-',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 24,
    predictedWeeklyDemandUnits: 125,
    safetyBufferRequiredUnits: 25,
    currentInventoryUnits: 145,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 94.9,
    seasonalSurgeFactor: 1.30,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0046',
    targetBloodGroup: 'O+',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 25,
    predictedWeeklyDemandUnits: 130,
    safetyBufferRequiredUnits: 26,
    currentInventoryUnits: 150,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 95.7,
    seasonalSurgeFactor: 1.35,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0047',
    targetBloodGroup: 'O-',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 26,
    predictedWeeklyDemandUnits: 135,
    safetyBufferRequiredUnits: 27,
    currentInventoryUnits: 155,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 96.5,
    seasonalSurgeFactor: 1.40,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0048',
    targetBloodGroup: 'A+',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 15,
    predictedWeeklyDemandUnits: 140,
    safetyBufferRequiredUnits: 28,
    currentInventoryUnits: 160,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 92.5,
    seasonalSurgeFactor: 1.05,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0049',
    targetBloodGroup: 'A-',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 16,
    predictedWeeklyDemandUnits: 145,
    safetyBufferRequiredUnits: 29,
    currentInventoryUnits: 165,
    netSurplusOrDeficitUnits: 20,
    forecastConfidenceIntervalPercentage: 93.3,
    seasonalSurgeFactor: 1.10,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0050',
    targetBloodGroup: 'B+',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 17,
    predictedWeeklyDemandUnits: 150,
    safetyBufferRequiredUnits: 20,
    currentInventoryUnits: 45,
    netSurplusOrDeficitUnits: -105,
    forecastConfidenceIntervalPercentage: 94.1,
    seasonalSurgeFactor: 1.15,
    riskOfStockoutPercentage: 55,
    recommendedEmergencyDonorCallCount: 315,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0051',
    targetBloodGroup: 'B-',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 18,
    predictedWeeklyDemandUnits: 155,
    safetyBufferRequiredUnits: 21,
    currentInventoryUnits: 50,
    netSurplusOrDeficitUnits: -105,
    forecastConfidenceIntervalPercentage: 94.9,
    seasonalSurgeFactor: 1.20,
    riskOfStockoutPercentage: 56,
    recommendedEmergencyDonorCallCount: 315,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0052',
    targetBloodGroup: 'AB+',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 19,
    predictedWeeklyDemandUnits: 160,
    safetyBufferRequiredUnits: 22,
    currentInventoryUnits: 55,
    netSurplusOrDeficitUnits: -105,
    forecastConfidenceIntervalPercentage: 95.7,
    seasonalSurgeFactor: 1.25,
    riskOfStockoutPercentage: 57,
    recommendedEmergencyDonorCallCount: 315,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0053',
    targetBloodGroup: 'AB-',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 20,
    predictedWeeklyDemandUnits: 165,
    safetyBufferRequiredUnits: 23,
    currentInventoryUnits: 60,
    netSurplusOrDeficitUnits: -105,
    forecastConfidenceIntervalPercentage: 96.5,
    seasonalSurgeFactor: 1.30,
    riskOfStockoutPercentage: 58,
    recommendedEmergencyDonorCallCount: 315,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0054',
    targetBloodGroup: 'O+',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 21,
    predictedWeeklyDemandUnits: 170,
    safetyBufferRequiredUnits: 24,
    currentInventoryUnits: 65,
    netSurplusOrDeficitUnits: -105,
    forecastConfidenceIntervalPercentage: 92.5,
    seasonalSurgeFactor: 1.35,
    riskOfStockoutPercentage: 59,
    recommendedEmergencyDonorCallCount: 315,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0055',
    targetBloodGroup: 'O-',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 22,
    predictedWeeklyDemandUnits: 175,
    safetyBufferRequiredUnits: 25,
    currentInventoryUnits: 70,
    netSurplusOrDeficitUnits: -105,
    forecastConfidenceIntervalPercentage: 93.3,
    seasonalSurgeFactor: 1.40,
    riskOfStockoutPercentage: 60,
    recommendedEmergencyDonorCallCount: 315,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0056',
    targetBloodGroup: 'A+',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 23,
    predictedWeeklyDemandUnits: 180,
    safetyBufferRequiredUnits: 26,
    currentInventoryUnits: 75,
    netSurplusOrDeficitUnits: -105,
    forecastConfidenceIntervalPercentage: 94.1,
    seasonalSurgeFactor: 1.05,
    riskOfStockoutPercentage: 61,
    recommendedEmergencyDonorCallCount: 315,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0057',
    targetBloodGroup: 'A-',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 24,
    predictedWeeklyDemandUnits: 185,
    safetyBufferRequiredUnits: 27,
    currentInventoryUnits: 80,
    netSurplusOrDeficitUnits: -105,
    forecastConfidenceIntervalPercentage: 94.9,
    seasonalSurgeFactor: 1.10,
    riskOfStockoutPercentage: 62,
    recommendedEmergencyDonorCallCount: 315,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0058',
    targetBloodGroup: 'B+',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 25,
    predictedWeeklyDemandUnits: 190,
    safetyBufferRequiredUnits: 28,
    currentInventoryUnits: 85,
    netSurplusOrDeficitUnits: -105,
    forecastConfidenceIntervalPercentage: 95.7,
    seasonalSurgeFactor: 1.15,
    riskOfStockoutPercentage: 63,
    recommendedEmergencyDonorCallCount: 315,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0059',
    targetBloodGroup: 'B-',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 26,
    predictedWeeklyDemandUnits: 195,
    safetyBufferRequiredUnits: 29,
    currentInventoryUnits: 90,
    netSurplusOrDeficitUnits: -105,
    forecastConfidenceIntervalPercentage: 96.5,
    seasonalSurgeFactor: 1.20,
    riskOfStockoutPercentage: 64,
    recommendedEmergencyDonorCallCount: 315,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0060',
    targetBloodGroup: 'AB+',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 15,
    predictedWeeklyDemandUnits: 50,
    safetyBufferRequiredUnits: 20,
    currentInventoryUnits: 95,
    netSurplusOrDeficitUnits: 45,
    forecastConfidenceIntervalPercentage: 92.5,
    seasonalSurgeFactor: 1.25,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0061',
    targetBloodGroup: 'AB-',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 16,
    predictedWeeklyDemandUnits: 55,
    safetyBufferRequiredUnits: 21,
    currentInventoryUnits: 100,
    netSurplusOrDeficitUnits: 45,
    forecastConfidenceIntervalPercentage: 93.3,
    seasonalSurgeFactor: 1.30,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0062',
    targetBloodGroup: 'O+',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 17,
    predictedWeeklyDemandUnits: 60,
    safetyBufferRequiredUnits: 22,
    currentInventoryUnits: 105,
    netSurplusOrDeficitUnits: 45,
    forecastConfidenceIntervalPercentage: 94.1,
    seasonalSurgeFactor: 1.35,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0063',
    targetBloodGroup: 'O-',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 18,
    predictedWeeklyDemandUnits: 65,
    safetyBufferRequiredUnits: 23,
    currentInventoryUnits: 110,
    netSurplusOrDeficitUnits: 45,
    forecastConfidenceIntervalPercentage: 94.9,
    seasonalSurgeFactor: 1.40,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0064',
    targetBloodGroup: 'A+',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 19,
    predictedWeeklyDemandUnits: 70,
    safetyBufferRequiredUnits: 24,
    currentInventoryUnits: 115,
    netSurplusOrDeficitUnits: 45,
    forecastConfidenceIntervalPercentage: 95.7,
    seasonalSurgeFactor: 1.05,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0065',
    targetBloodGroup: 'A-',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 20,
    predictedWeeklyDemandUnits: 75,
    safetyBufferRequiredUnits: 25,
    currentInventoryUnits: 120,
    netSurplusOrDeficitUnits: 45,
    forecastConfidenceIntervalPercentage: 96.5,
    seasonalSurgeFactor: 1.10,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0066',
    targetBloodGroup: 'B+',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 21,
    predictedWeeklyDemandUnits: 80,
    safetyBufferRequiredUnits: 26,
    currentInventoryUnits: 125,
    netSurplusOrDeficitUnits: 45,
    forecastConfidenceIntervalPercentage: 92.5,
    seasonalSurgeFactor: 1.15,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0067',
    targetBloodGroup: 'B-',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 22,
    predictedWeeklyDemandUnits: 85,
    safetyBufferRequiredUnits: 27,
    currentInventoryUnits: 130,
    netSurplusOrDeficitUnits: 45,
    forecastConfidenceIntervalPercentage: 93.3,
    seasonalSurgeFactor: 1.20,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0068',
    targetBloodGroup: 'AB+',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 23,
    predictedWeeklyDemandUnits: 90,
    safetyBufferRequiredUnits: 28,
    currentInventoryUnits: 135,
    netSurplusOrDeficitUnits: 45,
    forecastConfidenceIntervalPercentage: 94.1,
    seasonalSurgeFactor: 1.25,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0069',
    targetBloodGroup: 'AB-',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 24,
    predictedWeeklyDemandUnits: 95,
    safetyBufferRequiredUnits: 29,
    currentInventoryUnits: 140,
    netSurplusOrDeficitUnits: 45,
    forecastConfidenceIntervalPercentage: 94.9,
    seasonalSurgeFactor: 1.30,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0070',
    targetBloodGroup: 'O+',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 25,
    predictedWeeklyDemandUnits: 100,
    safetyBufferRequiredUnits: 20,
    currentInventoryUnits: 145,
    netSurplusOrDeficitUnits: 45,
    forecastConfidenceIntervalPercentage: 95.7,
    seasonalSurgeFactor: 1.35,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0071',
    targetBloodGroup: 'O-',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 26,
    predictedWeeklyDemandUnits: 105,
    safetyBufferRequiredUnits: 21,
    currentInventoryUnits: 150,
    netSurplusOrDeficitUnits: 45,
    forecastConfidenceIntervalPercentage: 96.5,
    seasonalSurgeFactor: 1.40,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0072',
    targetBloodGroup: 'A+',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 15,
    predictedWeeklyDemandUnits: 110,
    safetyBufferRequiredUnits: 22,
    currentInventoryUnits: 155,
    netSurplusOrDeficitUnits: 45,
    forecastConfidenceIntervalPercentage: 92.5,
    seasonalSurgeFactor: 1.05,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0073',
    targetBloodGroup: 'A-',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 16,
    predictedWeeklyDemandUnits: 115,
    safetyBufferRequiredUnits: 23,
    currentInventoryUnits: 160,
    netSurplusOrDeficitUnits: 45,
    forecastConfidenceIntervalPercentage: 93.3,
    seasonalSurgeFactor: 1.10,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0074',
    targetBloodGroup: 'B+',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 17,
    predictedWeeklyDemandUnits: 120,
    safetyBufferRequiredUnits: 24,
    currentInventoryUnits: 165,
    netSurplusOrDeficitUnits: 45,
    forecastConfidenceIntervalPercentage: 94.1,
    seasonalSurgeFactor: 1.15,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0075',
    targetBloodGroup: 'B-',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 18,
    predictedWeeklyDemandUnits: 125,
    safetyBufferRequiredUnits: 25,
    currentInventoryUnits: 45,
    netSurplusOrDeficitUnits: -80,
    forecastConfidenceIntervalPercentage: 94.9,
    seasonalSurgeFactor: 1.20,
    riskOfStockoutPercentage: 80,
    recommendedEmergencyDonorCallCount: 240,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0076',
    targetBloodGroup: 'AB+',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 19,
    predictedWeeklyDemandUnits: 130,
    safetyBufferRequiredUnits: 26,
    currentInventoryUnits: 50,
    netSurplusOrDeficitUnits: -80,
    forecastConfidenceIntervalPercentage: 95.7,
    seasonalSurgeFactor: 1.25,
    riskOfStockoutPercentage: 81,
    recommendedEmergencyDonorCallCount: 240,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0077',
    targetBloodGroup: 'AB-',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 20,
    predictedWeeklyDemandUnits: 135,
    safetyBufferRequiredUnits: 27,
    currentInventoryUnits: 55,
    netSurplusOrDeficitUnits: -80,
    forecastConfidenceIntervalPercentage: 96.5,
    seasonalSurgeFactor: 1.30,
    riskOfStockoutPercentage: 82,
    recommendedEmergencyDonorCallCount: 240,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0078',
    targetBloodGroup: 'O+',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 21,
    predictedWeeklyDemandUnits: 140,
    safetyBufferRequiredUnits: 28,
    currentInventoryUnits: 60,
    netSurplusOrDeficitUnits: -80,
    forecastConfidenceIntervalPercentage: 92.5,
    seasonalSurgeFactor: 1.35,
    riskOfStockoutPercentage: 83,
    recommendedEmergencyDonorCallCount: 240,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0079',
    targetBloodGroup: 'O-',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 22,
    predictedWeeklyDemandUnits: 145,
    safetyBufferRequiredUnits: 29,
    currentInventoryUnits: 65,
    netSurplusOrDeficitUnits: -80,
    forecastConfidenceIntervalPercentage: 93.3,
    seasonalSurgeFactor: 1.40,
    riskOfStockoutPercentage: 84,
    recommendedEmergencyDonorCallCount: 240,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0080',
    targetBloodGroup: 'A+',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 23,
    predictedWeeklyDemandUnits: 150,
    safetyBufferRequiredUnits: 20,
    currentInventoryUnits: 70,
    netSurplusOrDeficitUnits: -80,
    forecastConfidenceIntervalPercentage: 94.1,
    seasonalSurgeFactor: 1.05,
    riskOfStockoutPercentage: 45,
    recommendedEmergencyDonorCallCount: 240,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0081',
    targetBloodGroup: 'A-',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 24,
    predictedWeeklyDemandUnits: 155,
    safetyBufferRequiredUnits: 21,
    currentInventoryUnits: 75,
    netSurplusOrDeficitUnits: -80,
    forecastConfidenceIntervalPercentage: 94.9,
    seasonalSurgeFactor: 1.10,
    riskOfStockoutPercentage: 46,
    recommendedEmergencyDonorCallCount: 240,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0082',
    targetBloodGroup: 'B+',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 25,
    predictedWeeklyDemandUnits: 160,
    safetyBufferRequiredUnits: 22,
    currentInventoryUnits: 80,
    netSurplusOrDeficitUnits: -80,
    forecastConfidenceIntervalPercentage: 95.7,
    seasonalSurgeFactor: 1.15,
    riskOfStockoutPercentage: 47,
    recommendedEmergencyDonorCallCount: 240,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0083',
    targetBloodGroup: 'B-',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 26,
    predictedWeeklyDemandUnits: 165,
    safetyBufferRequiredUnits: 23,
    currentInventoryUnits: 85,
    netSurplusOrDeficitUnits: -80,
    forecastConfidenceIntervalPercentage: 96.5,
    seasonalSurgeFactor: 1.20,
    riskOfStockoutPercentage: 48,
    recommendedEmergencyDonorCallCount: 240,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0084',
    targetBloodGroup: 'AB+',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 15,
    predictedWeeklyDemandUnits: 170,
    safetyBufferRequiredUnits: 24,
    currentInventoryUnits: 90,
    netSurplusOrDeficitUnits: -80,
    forecastConfidenceIntervalPercentage: 92.5,
    seasonalSurgeFactor: 1.25,
    riskOfStockoutPercentage: 49,
    recommendedEmergencyDonorCallCount: 240,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0085',
    targetBloodGroup: 'AB-',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 16,
    predictedWeeklyDemandUnits: 175,
    safetyBufferRequiredUnits: 25,
    currentInventoryUnits: 95,
    netSurplusOrDeficitUnits: -80,
    forecastConfidenceIntervalPercentage: 93.3,
    seasonalSurgeFactor: 1.30,
    riskOfStockoutPercentage: 50,
    recommendedEmergencyDonorCallCount: 240,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0086',
    targetBloodGroup: 'O+',
    componentType: 'FFP',
    historicalDailyConsumptionUnits: 17,
    predictedWeeklyDemandUnits: 180,
    safetyBufferRequiredUnits: 26,
    currentInventoryUnits: 100,
    netSurplusOrDeficitUnits: -80,
    forecastConfidenceIntervalPercentage: 94.1,
    seasonalSurgeFactor: 1.35,
    riskOfStockoutPercentage: 51,
    recommendedEmergencyDonorCallCount: 240,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0087',
    targetBloodGroup: 'O-',
    componentType: 'PLATELETS',
    historicalDailyConsumptionUnits: 18,
    predictedWeeklyDemandUnits: 185,
    safetyBufferRequiredUnits: 27,
    currentInventoryUnits: 105,
    netSurplusOrDeficitUnits: -80,
    forecastConfidenceIntervalPercentage: 94.9,
    seasonalSurgeFactor: 1.40,
    riskOfStockoutPercentage: 52,
    recommendedEmergencyDonorCallCount: 240,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0088',
    targetBloodGroup: 'A+',
    componentType: 'CRYOPRECIPITATE',
    historicalDailyConsumptionUnits: 19,
    predictedWeeklyDemandUnits: 190,
    safetyBufferRequiredUnits: 28,
    currentInventoryUnits: 110,
    netSurplusOrDeficitUnits: -80,
    forecastConfidenceIntervalPercentage: 95.7,
    seasonalSurgeFactor: 1.05,
    riskOfStockoutPercentage: 53,
    recommendedEmergencyDonorCallCount: 240,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0089',
    targetBloodGroup: 'A-',
    componentType: 'WHOLE_BLOOD',
    historicalDailyConsumptionUnits: 20,
    predictedWeeklyDemandUnits: 195,
    safetyBufferRequiredUnits: 29,
    currentInventoryUnits: 115,
    netSurplusOrDeficitUnits: -80,
    forecastConfidenceIntervalPercentage: 96.5,
    seasonalSurgeFactor: 1.10,
    riskOfStockoutPercentage: 54,
    recommendedEmergencyDonorCallCount: 240,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
  {
    forecastId: 'FCST-SMSW-0090',
    targetBloodGroup: 'B+',
    componentType: 'PRBC',
    historicalDailyConsumptionUnits: 21,
    predictedWeeklyDemandUnits: 50,
    safetyBufferRequiredUnits: 20,
    currentInventoryUnits: 120,
    netSurplusOrDeficitUnits: 70,
    forecastConfidenceIntervalPercentage: 92.5,
    seasonalSurgeFactor: 1.15,
    riskOfStockoutPercentage: 5,
    recommendedEmergencyDonorCallCount: 0,
    computedTimestampIso: '2026-09-09T08:00:00.000Z',
  },
];

export function computeSafetyBufferStock(dailyConsumption: number, leadTimeDays = 3, serviceLevelZScore = 1.96): number {
  const stdDevConsumption = dailyConsumption * 0.25;
  return Math.ceil(serviceLevelZScore * Math.sqrt(leadTimeDays) * stdDevConsumption);
}

export function isEmergencyMobilizationNeeded(forecast: RecallCampaignRecord): boolean {
  return forecast.netSurplusOrDeficitUnits < 0 || forecast.riskOfStockoutPercentage > 30;
}
