/**
 * BloodBridge Cold Chain Telemetry Engine — Modbus RTU/TCP Walk-in Cold Room Telemetry Controller
 * Real-time continuous thermal monitoring and degradation kinetics.
 */

export interface ModbusChamberRecord {
  id: string;
  sensorDeviceId: string;
  storageUnitIdentifier: string;
  componentCategory: 'PRBC' | 'FFP' | 'PLATELETS' | 'CRYOPRECIPITATE' | 'WHOLE_BLOOD';
  currentTemperatureCelsius: number;
  targetRangeMinCelsius: number;
  targetRangeMaxCelsius: number;
  meanKineticTemperature24h: number;
  thermalExcursionDurationSeconds: number;
  kineticDegradationIndex: number;
  complianceStatus: 'OPTIMAL' | 'WARNING_TREND' | 'CRITICAL_EXCURSION' | 'COMPROMISED_QUARANTINE';
  timestampIso: string;
  batteryLevelPercentage: number;
  signalRssiDbm: number;
  cryptographicTelemetrySignature: string;
}

export const MODBUSRTUCHAMBERINTERFACE_TELEMETRY_LOGS: ModbusChamberRecord[] = [
  {
    id: 'TEL-MODB-0001',
    sensorDeviceId: 'SENS-IOT-MOD-1001',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-1',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 2.80,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.95,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0150,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T11:07:00.000Z',
    batteryLevelPercentage: 94,
    signalRssiDbm: -66,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000001',
  },
  {
    id: 'TEL-MODB-0002',
    sensorDeviceId: 'SENS-IOT-MOD-1002',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-2',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 3.10,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.25,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0300,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T12:14:00.000Z',
    batteryLevelPercentage: 93,
    signalRssiDbm: -67,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000002',
  },
  {
    id: 'TEL-MODB-0003',
    sensorDeviceId: 'SENS-IOT-MOD-1003',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-3',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 3.40,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.55,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0450,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T13:21:00.000Z',
    batteryLevelPercentage: 92,
    signalRssiDbm: -68,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000003',
  },
  {
    id: 'TEL-MODB-0004',
    sensorDeviceId: 'SENS-IOT-MOD-1004',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-4',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 3.70,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.85,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0600,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T14:28:00.000Z',
    batteryLevelPercentage: 91,
    signalRssiDbm: -69,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000004',
  },
  {
    id: 'TEL-MODB-0005',
    sensorDeviceId: 'SENS-IOT-MOD-1005',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-5',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 4.00,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.15,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0750,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T15:35:00.000Z',
    batteryLevelPercentage: 90,
    signalRssiDbm: -70,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000005',
  },
  {
    id: 'TEL-MODB-0006',
    sensorDeviceId: 'SENS-IOT-MOD-1006',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-6',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 4.30,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.45,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0900,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T16:42:00.000Z',
    batteryLevelPercentage: 89,
    signalRssiDbm: -71,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000006',
  },
  {
    id: 'TEL-MODB-0007',
    sensorDeviceId: 'SENS-IOT-MOD-1007',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-7',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 4.60,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.75,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1050,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T17:49:00.000Z',
    batteryLevelPercentage: 88,
    signalRssiDbm: -72,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000007',
  },
  {
    id: 'TEL-MODB-0008',
    sensorDeviceId: 'SENS-IOT-MOD-1008',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-8',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 4.90,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.05,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1200,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T18:56:00.000Z',
    batteryLevelPercentage: 87,
    signalRssiDbm: -73,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000008',
  },
  {
    id: 'TEL-MODB-0009',
    sensorDeviceId: 'SENS-IOT-MOD-1009',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-1',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 5.20,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.35,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1350,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T19:03:00.000Z',
    batteryLevelPercentage: 86,
    signalRssiDbm: -74,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000009',
  },
  {
    id: 'TEL-MODB-0010',
    sensorDeviceId: 'SENS-IOT-MOD-1010',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-2',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 5.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0000,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T20:10:00.000Z',
    batteryLevelPercentage: 85,
    signalRssiDbm: -75,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000010',
  },
  {
    id: 'TEL-MODB-0011',
    sensorDeviceId: 'SENS-IOT-MOD-1011',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-3',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 2.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0150,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T21:17:00.000Z',
    batteryLevelPercentage: 84,
    signalRssiDbm: -76,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000011',
  },
  {
    id: 'TEL-MODB-0012',
    sensorDeviceId: 'SENS-IOT-MOD-1012',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-4',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 2.80,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.95,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0300,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T10:24:00.000Z',
    batteryLevelPercentage: 83,
    signalRssiDbm: -77,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000012',
  },
  {
    id: 'TEL-MODB-0013',
    sensorDeviceId: 'SENS-IOT-MOD-1013',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-5',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 3.10,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.25,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0450,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T11:31:00.000Z',
    batteryLevelPercentage: 82,
    signalRssiDbm: -78,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000013',
  },
  {
    id: 'TEL-MODB-0014',
    sensorDeviceId: 'SENS-IOT-MOD-1014',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-6',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 3.40,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.55,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0600,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T12:38:00.000Z',
    batteryLevelPercentage: 81,
    signalRssiDbm: -79,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000014',
  },
  {
    id: 'TEL-MODB-0015',
    sensorDeviceId: 'SENS-IOT-MOD-1015',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-7',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 3.70,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.85,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0750,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T13:45:00.000Z',
    batteryLevelPercentage: 80,
    signalRssiDbm: -80,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000015',
  },
  {
    id: 'TEL-MODB-0016',
    sensorDeviceId: 'SENS-IOT-MOD-1016',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-8',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 4.00,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.15,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0900,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T14:52:00.000Z',
    batteryLevelPercentage: 79,
    signalRssiDbm: -81,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000016',
  },
  {
    id: 'TEL-MODB-0017',
    sensorDeviceId: 'SENS-IOT-MOD-1017',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-1',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 4.30,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.45,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1050,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T15:59:00.000Z',
    batteryLevelPercentage: 78,
    signalRssiDbm: -82,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000017',
  },
  {
    id: 'TEL-MODB-0018',
    sensorDeviceId: 'SENS-IOT-MOD-1018',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-2',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 4.60,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.75,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1200,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T16:06:00.000Z',
    batteryLevelPercentage: 77,
    signalRssiDbm: -83,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000018',
  },
  {
    id: 'TEL-MODB-0019',
    sensorDeviceId: 'SENS-IOT-MOD-1019',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-3',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 4.90,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.05,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1350,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T17:13:00.000Z',
    batteryLevelPercentage: 76,
    signalRssiDbm: -84,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000019',
  },
  {
    id: 'TEL-MODB-0020',
    sensorDeviceId: 'SENS-IOT-MOD-1020',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-4',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 5.20,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.35,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0000,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T18:20:00.000Z',
    batteryLevelPercentage: 75,
    signalRssiDbm: -85,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000020',
  },
  {
    id: 'TEL-MODB-0021',
    sensorDeviceId: 'SENS-IOT-MOD-1021',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-5',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 5.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0150,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T19:27:00.000Z',
    batteryLevelPercentage: 74,
    signalRssiDbm: -86,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000021',
  },
  {
    id: 'TEL-MODB-0022',
    sensorDeviceId: 'SENS-IOT-MOD-1022',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-6',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 2.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0300,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T20:34:00.000Z',
    batteryLevelPercentage: 73,
    signalRssiDbm: -87,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000022',
  },
  {
    id: 'TEL-MODB-0023',
    sensorDeviceId: 'SENS-IOT-MOD-1023',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-7',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 2.80,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.95,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0450,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T21:41:00.000Z',
    batteryLevelPercentage: 72,
    signalRssiDbm: -88,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000023',
  },
  {
    id: 'TEL-MODB-0024',
    sensorDeviceId: 'SENS-IOT-MOD-1024',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-8',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 3.10,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.25,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0600,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T10:48:00.000Z',
    batteryLevelPercentage: 71,
    signalRssiDbm: -89,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000024',
  },
  {
    id: 'TEL-MODB-0025',
    sensorDeviceId: 'SENS-IOT-MOD-1025',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-1',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 3.40,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.55,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0750,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T11:55:00.000Z',
    batteryLevelPercentage: 70,
    signalRssiDbm: -65,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000025',
  },
  {
    id: 'TEL-MODB-0026',
    sensorDeviceId: 'SENS-IOT-MOD-1026',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-2',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 3.70,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.85,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0900,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T12:02:00.000Z',
    batteryLevelPercentage: 69,
    signalRssiDbm: -66,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000026',
  },
  {
    id: 'TEL-MODB-0027',
    sensorDeviceId: 'SENS-IOT-MOD-1027',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-3',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 4.00,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.15,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1050,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T13:09:00.000Z',
    batteryLevelPercentage: 68,
    signalRssiDbm: -67,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000027',
  },
  {
    id: 'TEL-MODB-0028',
    sensorDeviceId: 'SENS-IOT-MOD-1028',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-4',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 4.30,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.45,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1200,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T14:16:00.000Z',
    batteryLevelPercentage: 67,
    signalRssiDbm: -68,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000028',
  },
  {
    id: 'TEL-MODB-0029',
    sensorDeviceId: 'SENS-IOT-MOD-1029',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-5',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 4.60,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.75,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1350,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T15:23:00.000Z',
    batteryLevelPercentage: 66,
    signalRssiDbm: -69,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000029',
  },
  {
    id: 'TEL-MODB-0030',
    sensorDeviceId: 'SENS-IOT-MOD-1030',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-6',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 4.90,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.05,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0000,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T16:30:00.000Z',
    batteryLevelPercentage: 95,
    signalRssiDbm: -70,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000030',
  },
  {
    id: 'TEL-MODB-0031',
    sensorDeviceId: 'SENS-IOT-MOD-1031',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-7',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 5.20,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.35,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0150,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T17:37:00.000Z',
    batteryLevelPercentage: 94,
    signalRssiDbm: -71,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000031',
  },
  {
    id: 'TEL-MODB-0032',
    sensorDeviceId: 'SENS-IOT-MOD-1032',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-8',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 5.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0300,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T18:44:00.000Z',
    batteryLevelPercentage: 93,
    signalRssiDbm: -72,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000032',
  },
  {
    id: 'TEL-MODB-0033',
    sensorDeviceId: 'SENS-IOT-MOD-1033',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-1',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 2.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0450,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T19:51:00.000Z',
    batteryLevelPercentage: 92,
    signalRssiDbm: -73,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000033',
  },
  {
    id: 'TEL-MODB-0034',
    sensorDeviceId: 'SENS-IOT-MOD-1034',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-2',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 2.80,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.95,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0600,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T20:58:00.000Z',
    batteryLevelPercentage: 91,
    signalRssiDbm: -74,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000034',
  },
  {
    id: 'TEL-MODB-0035',
    sensorDeviceId: 'SENS-IOT-MOD-1035',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-3',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 3.10,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.25,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0750,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T21:05:00.000Z',
    batteryLevelPercentage: 90,
    signalRssiDbm: -75,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000035',
  },
  {
    id: 'TEL-MODB-0036',
    sensorDeviceId: 'SENS-IOT-MOD-1036',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-4',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 3.40,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.55,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0900,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T10:12:00.000Z',
    batteryLevelPercentage: 89,
    signalRssiDbm: -76,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000036',
  },
  {
    id: 'TEL-MODB-0037',
    sensorDeviceId: 'SENS-IOT-MOD-1037',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-5',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 3.70,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.85,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1050,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T11:19:00.000Z',
    batteryLevelPercentage: 88,
    signalRssiDbm: -77,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000037',
  },
  {
    id: 'TEL-MODB-0038',
    sensorDeviceId: 'SENS-IOT-MOD-1038',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-6',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 4.00,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.15,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1200,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T12:26:00.000Z',
    batteryLevelPercentage: 87,
    signalRssiDbm: -78,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000038',
  },
  {
    id: 'TEL-MODB-0039',
    sensorDeviceId: 'SENS-IOT-MOD-1039',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-7',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 4.30,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.45,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1350,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T13:33:00.000Z',
    batteryLevelPercentage: 86,
    signalRssiDbm: -79,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000039',
  },
  {
    id: 'TEL-MODB-0040',
    sensorDeviceId: 'SENS-IOT-MOD-1040',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-8',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 4.60,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.75,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0000,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T14:40:00.000Z',
    batteryLevelPercentage: 85,
    signalRssiDbm: -80,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000040',
  },
  {
    id: 'TEL-MODB-0041',
    sensorDeviceId: 'SENS-IOT-MOD-1041',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-1',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 4.90,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.05,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0150,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T15:47:00.000Z',
    batteryLevelPercentage: 84,
    signalRssiDbm: -81,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000041',
  },
  {
    id: 'TEL-MODB-0042',
    sensorDeviceId: 'SENS-IOT-MOD-1042',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-2',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 5.20,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.35,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0300,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T16:54:00.000Z',
    batteryLevelPercentage: 83,
    signalRssiDbm: -82,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000042',
  },
  {
    id: 'TEL-MODB-0043',
    sensorDeviceId: 'SENS-IOT-MOD-1043',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-3',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 5.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0450,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T17:01:00.000Z',
    batteryLevelPercentage: 82,
    signalRssiDbm: -83,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000043',
  },
  {
    id: 'TEL-MODB-0044',
    sensorDeviceId: 'SENS-IOT-MOD-1044',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-4',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 2.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0600,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T18:08:00.000Z',
    batteryLevelPercentage: 81,
    signalRssiDbm: -84,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000044',
  },
  {
    id: 'TEL-MODB-0045',
    sensorDeviceId: 'SENS-IOT-MOD-1045',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-5',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 2.80,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.95,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0750,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T19:15:00.000Z',
    batteryLevelPercentage: 80,
    signalRssiDbm: -85,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000045',
  },
  {
    id: 'TEL-MODB-0046',
    sensorDeviceId: 'SENS-IOT-MOD-1046',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-6',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 3.10,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.25,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0900,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T20:22:00.000Z',
    batteryLevelPercentage: 79,
    signalRssiDbm: -86,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000046',
  },
  {
    id: 'TEL-MODB-0047',
    sensorDeviceId: 'SENS-IOT-MOD-1047',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-7',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 3.40,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.55,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1050,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T21:29:00.000Z',
    batteryLevelPercentage: 78,
    signalRssiDbm: -87,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000047',
  },
  {
    id: 'TEL-MODB-0048',
    sensorDeviceId: 'SENS-IOT-MOD-1048',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-8',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 3.70,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.85,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1200,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T10:36:00.000Z',
    batteryLevelPercentage: 77,
    signalRssiDbm: -88,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000048',
  },
  {
    id: 'TEL-MODB-0049',
    sensorDeviceId: 'SENS-IOT-MOD-1049',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-1',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 4.00,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.15,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1350,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T11:43:00.000Z',
    batteryLevelPercentage: 76,
    signalRssiDbm: -89,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000049',
  },
  {
    id: 'TEL-MODB-0050',
    sensorDeviceId: 'SENS-IOT-MOD-1050',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-2',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 4.30,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.45,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0000,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T12:50:00.000Z',
    batteryLevelPercentage: 75,
    signalRssiDbm: -65,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000050',
  },
  {
    id: 'TEL-MODB-0051',
    sensorDeviceId: 'SENS-IOT-MOD-1051',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-3',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 4.60,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.75,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0150,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T13:57:00.000Z',
    batteryLevelPercentage: 74,
    signalRssiDbm: -66,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000051',
  },
  {
    id: 'TEL-MODB-0052',
    sensorDeviceId: 'SENS-IOT-MOD-1052',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-4',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 4.90,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.05,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0300,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T14:04:00.000Z',
    batteryLevelPercentage: 73,
    signalRssiDbm: -67,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000052',
  },
  {
    id: 'TEL-MODB-0053',
    sensorDeviceId: 'SENS-IOT-MOD-1053',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-5',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 5.20,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.35,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0450,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T15:11:00.000Z',
    batteryLevelPercentage: 72,
    signalRssiDbm: -68,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000053',
  },
  {
    id: 'TEL-MODB-0054',
    sensorDeviceId: 'SENS-IOT-MOD-1054',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-6',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 5.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0600,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T16:18:00.000Z',
    batteryLevelPercentage: 71,
    signalRssiDbm: -69,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000054',
  },
  {
    id: 'TEL-MODB-0055',
    sensorDeviceId: 'SENS-IOT-MOD-1055',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-7',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 2.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0750,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T17:25:00.000Z',
    batteryLevelPercentage: 70,
    signalRssiDbm: -70,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000055',
  },
  {
    id: 'TEL-MODB-0056',
    sensorDeviceId: 'SENS-IOT-MOD-1056',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-8',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 2.80,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.95,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0900,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T18:32:00.000Z',
    batteryLevelPercentage: 69,
    signalRssiDbm: -71,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000056',
  },
  {
    id: 'TEL-MODB-0057',
    sensorDeviceId: 'SENS-IOT-MOD-1057',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-1',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 3.10,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.25,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1050,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T19:39:00.000Z',
    batteryLevelPercentage: 68,
    signalRssiDbm: -72,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000057',
  },
  {
    id: 'TEL-MODB-0058',
    sensorDeviceId: 'SENS-IOT-MOD-1058',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-2',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 3.40,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.55,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1200,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T20:46:00.000Z',
    batteryLevelPercentage: 67,
    signalRssiDbm: -73,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000058',
  },
  {
    id: 'TEL-MODB-0059',
    sensorDeviceId: 'SENS-IOT-MOD-1059',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-3',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 3.70,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.85,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1350,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T21:53:00.000Z',
    batteryLevelPercentage: 66,
    signalRssiDbm: -74,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000059',
  },
  {
    id: 'TEL-MODB-0060',
    sensorDeviceId: 'SENS-IOT-MOD-1060',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-4',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 4.00,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.15,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0000,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T10:00:00.000Z',
    batteryLevelPercentage: 95,
    signalRssiDbm: -75,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000060',
  },
  {
    id: 'TEL-MODB-0061',
    sensorDeviceId: 'SENS-IOT-MOD-1061',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-5',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 4.30,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.45,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0150,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T11:07:00.000Z',
    batteryLevelPercentage: 94,
    signalRssiDbm: -76,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000061',
  },
  {
    id: 'TEL-MODB-0062',
    sensorDeviceId: 'SENS-IOT-MOD-1062',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-6',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 4.60,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.75,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0300,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T12:14:00.000Z',
    batteryLevelPercentage: 93,
    signalRssiDbm: -77,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000062',
  },
  {
    id: 'TEL-MODB-0063',
    sensorDeviceId: 'SENS-IOT-MOD-1063',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-7',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 4.90,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.05,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0450,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T13:21:00.000Z',
    batteryLevelPercentage: 92,
    signalRssiDbm: -78,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000063',
  },
  {
    id: 'TEL-MODB-0064',
    sensorDeviceId: 'SENS-IOT-MOD-1064',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-8',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 5.20,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.35,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0600,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T14:28:00.000Z',
    batteryLevelPercentage: 91,
    signalRssiDbm: -79,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000064',
  },
  {
    id: 'TEL-MODB-0065',
    sensorDeviceId: 'SENS-IOT-MOD-1065',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-1',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 5.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0750,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T15:35:00.000Z',
    batteryLevelPercentage: 90,
    signalRssiDbm: -80,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000065',
  },
  {
    id: 'TEL-MODB-0066',
    sensorDeviceId: 'SENS-IOT-MOD-1066',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-2',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 2.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0900,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T16:42:00.000Z',
    batteryLevelPercentage: 89,
    signalRssiDbm: -81,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000066',
  },
  {
    id: 'TEL-MODB-0067',
    sensorDeviceId: 'SENS-IOT-MOD-1067',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-3',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 2.80,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.95,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1050,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T17:49:00.000Z',
    batteryLevelPercentage: 88,
    signalRssiDbm: -82,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000067',
  },
  {
    id: 'TEL-MODB-0068',
    sensorDeviceId: 'SENS-IOT-MOD-1068',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-4',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 3.10,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.25,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1200,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T18:56:00.000Z',
    batteryLevelPercentage: 87,
    signalRssiDbm: -83,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000068',
  },
  {
    id: 'TEL-MODB-0069',
    sensorDeviceId: 'SENS-IOT-MOD-1069',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-5',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 3.40,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.55,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1350,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T19:03:00.000Z',
    batteryLevelPercentage: 86,
    signalRssiDbm: -84,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000069',
  },
  {
    id: 'TEL-MODB-0070',
    sensorDeviceId: 'SENS-IOT-MOD-1070',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-6',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 3.70,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.85,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0000,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T20:10:00.000Z',
    batteryLevelPercentage: 85,
    signalRssiDbm: -85,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000070',
  },
  {
    id: 'TEL-MODB-0071',
    sensorDeviceId: 'SENS-IOT-MOD-1071',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-7',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 4.00,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.15,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0150,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T21:17:00.000Z',
    batteryLevelPercentage: 84,
    signalRssiDbm: -86,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000071',
  },
  {
    id: 'TEL-MODB-0072',
    sensorDeviceId: 'SENS-IOT-MOD-1072',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-8',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 4.30,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.45,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0300,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T10:24:00.000Z',
    batteryLevelPercentage: 83,
    signalRssiDbm: -87,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000072',
  },
  {
    id: 'TEL-MODB-0073',
    sensorDeviceId: 'SENS-IOT-MOD-1073',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-1',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 4.60,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.75,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0450,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T11:31:00.000Z',
    batteryLevelPercentage: 82,
    signalRssiDbm: -88,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000073',
  },
  {
    id: 'TEL-MODB-0074',
    sensorDeviceId: 'SENS-IOT-MOD-1074',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-2',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 4.90,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.05,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0600,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T12:38:00.000Z',
    batteryLevelPercentage: 81,
    signalRssiDbm: -89,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000074',
  },
  {
    id: 'TEL-MODB-0075',
    sensorDeviceId: 'SENS-IOT-MOD-1075',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-3',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 5.20,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.35,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0750,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T13:45:00.000Z',
    batteryLevelPercentage: 80,
    signalRssiDbm: -65,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000075',
  },
  {
    id: 'TEL-MODB-0076',
    sensorDeviceId: 'SENS-IOT-MOD-1076',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-4',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 5.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0900,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T14:52:00.000Z',
    batteryLevelPercentage: 79,
    signalRssiDbm: -66,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000076',
  },
  {
    id: 'TEL-MODB-0077',
    sensorDeviceId: 'SENS-IOT-MOD-1077',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-5',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 2.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1050,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T15:59:00.000Z',
    batteryLevelPercentage: 78,
    signalRssiDbm: -67,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000077',
  },
  {
    id: 'TEL-MODB-0078',
    sensorDeviceId: 'SENS-IOT-MOD-1078',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-6',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 2.80,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.95,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1200,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T16:06:00.000Z',
    batteryLevelPercentage: 77,
    signalRssiDbm: -68,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000078',
  },
  {
    id: 'TEL-MODB-0079',
    sensorDeviceId: 'SENS-IOT-MOD-1079',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-7',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 3.10,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.25,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1350,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T17:13:00.000Z',
    batteryLevelPercentage: 76,
    signalRssiDbm: -69,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000079',
  },
  {
    id: 'TEL-MODB-0080',
    sensorDeviceId: 'SENS-IOT-MOD-1080',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-8',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 3.40,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.55,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0000,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T18:20:00.000Z',
    batteryLevelPercentage: 75,
    signalRssiDbm: -70,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000080',
  },
  {
    id: 'TEL-MODB-0081',
    sensorDeviceId: 'SENS-IOT-MOD-1081',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-1',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 3.70,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.85,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0150,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T19:27:00.000Z',
    batteryLevelPercentage: 74,
    signalRssiDbm: -71,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000081',
  },
  {
    id: 'TEL-MODB-0082',
    sensorDeviceId: 'SENS-IOT-MOD-1082',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-2',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 4.00,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.15,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0300,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T20:34:00.000Z',
    batteryLevelPercentage: 73,
    signalRssiDbm: -72,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000082',
  },
  {
    id: 'TEL-MODB-0083',
    sensorDeviceId: 'SENS-IOT-MOD-1083',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-3',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 4.30,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.45,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0450,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T21:41:00.000Z',
    batteryLevelPercentage: 72,
    signalRssiDbm: -73,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000083',
  },
  {
    id: 'TEL-MODB-0084',
    sensorDeviceId: 'SENS-IOT-MOD-1084',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-4',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 4.60,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.75,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0600,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T10:48:00.000Z',
    batteryLevelPercentage: 71,
    signalRssiDbm: -74,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000084',
  },
  {
    id: 'TEL-MODB-0085',
    sensorDeviceId: 'SENS-IOT-MOD-1085',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-5',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 4.90,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.05,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0750,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T11:55:00.000Z',
    batteryLevelPercentage: 70,
    signalRssiDbm: -75,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000085',
  },
  {
    id: 'TEL-MODB-0086',
    sensorDeviceId: 'SENS-IOT-MOD-1086',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-6',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 5.20,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.35,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0900,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T12:02:00.000Z',
    batteryLevelPercentage: 69,
    signalRssiDbm: -76,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000086',
  },
  {
    id: 'TEL-MODB-0087',
    sensorDeviceId: 'SENS-IOT-MOD-1087',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-7',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 5.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1050,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T13:09:00.000Z',
    batteryLevelPercentage: 68,
    signalRssiDbm: -77,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000087',
  },
  {
    id: 'TEL-MODB-0088',
    sensorDeviceId: 'SENS-IOT-MOD-1088',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-8',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 2.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1200,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T14:16:00.000Z',
    batteryLevelPercentage: 67,
    signalRssiDbm: -78,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000088',
  },
  {
    id: 'TEL-MODB-0089',
    sensorDeviceId: 'SENS-IOT-MOD-1089',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-1',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 2.80,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.95,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1350,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T15:23:00.000Z',
    batteryLevelPercentage: 66,
    signalRssiDbm: -79,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000089',
  },
  {
    id: 'TEL-MODB-0090',
    sensorDeviceId: 'SENS-IOT-MOD-1090',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-2',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 3.10,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.25,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0000,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T16:30:00.000Z',
    batteryLevelPercentage: 95,
    signalRssiDbm: -80,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000090',
  },
  {
    id: 'TEL-MODB-0091',
    sensorDeviceId: 'SENS-IOT-MOD-1091',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-3',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 3.40,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.55,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0150,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T17:37:00.000Z',
    batteryLevelPercentage: 94,
    signalRssiDbm: -81,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000091',
  },
  {
    id: 'TEL-MODB-0092',
    sensorDeviceId: 'SENS-IOT-MOD-1092',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-4',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 3.70,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.85,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0300,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T18:44:00.000Z',
    batteryLevelPercentage: 93,
    signalRssiDbm: -82,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000092',
  },
  {
    id: 'TEL-MODB-0093',
    sensorDeviceId: 'SENS-IOT-MOD-1093',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-5',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 4.00,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.15,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0450,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T19:51:00.000Z',
    batteryLevelPercentage: 92,
    signalRssiDbm: -83,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000093',
  },
  {
    id: 'TEL-MODB-0094',
    sensorDeviceId: 'SENS-IOT-MOD-1094',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-6',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 4.30,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.45,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0600,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T20:58:00.000Z',
    batteryLevelPercentage: 91,
    signalRssiDbm: -84,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000094',
  },
  {
    id: 'TEL-MODB-0095',
    sensorDeviceId: 'SENS-IOT-MOD-1095',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-7',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 4.60,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.75,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0750,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T21:05:00.000Z',
    batteryLevelPercentage: 90,
    signalRssiDbm: -85,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000095',
  },
  {
    id: 'TEL-MODB-0096',
    sensorDeviceId: 'SENS-IOT-MOD-1096',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-8',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 4.90,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.05,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0900,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T10:12:00.000Z',
    batteryLevelPercentage: 89,
    signalRssiDbm: -86,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000096',
  },
  {
    id: 'TEL-MODB-0097',
    sensorDeviceId: 'SENS-IOT-MOD-1097',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-1',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 5.20,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.35,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1050,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T11:19:00.000Z',
    batteryLevelPercentage: 88,
    signalRssiDbm: -87,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000097',
  },
  {
    id: 'TEL-MODB-0098',
    sensorDeviceId: 'SENS-IOT-MOD-1098',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-2',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 5.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1200,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T12:26:00.000Z',
    batteryLevelPercentage: 87,
    signalRssiDbm: -88,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000098',
  },
  {
    id: 'TEL-MODB-0099',
    sensorDeviceId: 'SENS-IOT-MOD-1099',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-3',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 2.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1350,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T13:33:00.000Z',
    batteryLevelPercentage: 86,
    signalRssiDbm: -89,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000099',
  },
  {
    id: 'TEL-MODB-0100',
    sensorDeviceId: 'SENS-IOT-MOD-1100',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-4',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 2.80,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.95,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0000,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T14:40:00.000Z',
    batteryLevelPercentage: 85,
    signalRssiDbm: -65,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000100',
  },
  {
    id: 'TEL-MODB-0101',
    sensorDeviceId: 'SENS-IOT-MOD-1101',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-5',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 3.10,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.25,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0150,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T15:47:00.000Z',
    batteryLevelPercentage: 84,
    signalRssiDbm: -66,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000101',
  },
  {
    id: 'TEL-MODB-0102',
    sensorDeviceId: 'SENS-IOT-MOD-1102',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-6',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 3.40,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.55,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0300,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T16:54:00.000Z',
    batteryLevelPercentage: 83,
    signalRssiDbm: -67,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000102',
  },
  {
    id: 'TEL-MODB-0103',
    sensorDeviceId: 'SENS-IOT-MOD-1103',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-7',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 3.70,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.85,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0450,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T17:01:00.000Z',
    batteryLevelPercentage: 82,
    signalRssiDbm: -68,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000103',
  },
  {
    id: 'TEL-MODB-0104',
    sensorDeviceId: 'SENS-IOT-MOD-1104',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-8',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 4.00,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.15,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0600,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T18:08:00.000Z',
    batteryLevelPercentage: 81,
    signalRssiDbm: -69,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000104',
  },
  {
    id: 'TEL-MODB-0105',
    sensorDeviceId: 'SENS-IOT-MOD-1105',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-1',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 4.30,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.45,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0750,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T19:15:00.000Z',
    batteryLevelPercentage: 80,
    signalRssiDbm: -70,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000105',
  },
  {
    id: 'TEL-MODB-0106',
    sensorDeviceId: 'SENS-IOT-MOD-1106',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-2',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 4.60,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 4.75,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0900,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T20:22:00.000Z',
    batteryLevelPercentage: 79,
    signalRssiDbm: -71,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000106',
  },
  {
    id: 'TEL-MODB-0107',
    sensorDeviceId: 'SENS-IOT-MOD-1107',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-3',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 4.90,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.05,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1050,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T21:29:00.000Z',
    batteryLevelPercentage: 78,
    signalRssiDbm: -72,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000107',
  },
  {
    id: 'TEL-MODB-0108',
    sensorDeviceId: 'SENS-IOT-MOD-1108',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-4',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 5.20,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.35,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1200,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T10:36:00.000Z',
    batteryLevelPercentage: 77,
    signalRssiDbm: -73,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000108',
  },
  {
    id: 'TEL-MODB-0109',
    sensorDeviceId: 'SENS-IOT-MOD-1109',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-5',
    componentCategory: 'WHOLE_BLOOD',
    currentTemperatureCelsius: 5.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 5.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.1350,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T11:43:00.000Z',
    batteryLevelPercentage: 76,
    signalRssiDbm: -74,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000109',
  },
  {
    id: 'TEL-MODB-0110',
    sensorDeviceId: 'SENS-IOT-MOD-1110',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-6',
    componentCategory: 'PRBC',
    currentTemperatureCelsius: 2.50,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.65,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0000,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T12:50:00.000Z',
    batteryLevelPercentage: 75,
    signalRssiDbm: -75,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000110',
  },
  {
    id: 'TEL-MODB-0111',
    sensorDeviceId: 'SENS-IOT-MOD-1111',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-7',
    componentCategory: 'FFP',
    currentTemperatureCelsius: 2.80,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 2.95,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0150,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T13:57:00.000Z',
    batteryLevelPercentage: 74,
    signalRssiDbm: -76,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000111',
  },
  {
    id: 'TEL-MODB-0112',
    sensorDeviceId: 'SENS-IOT-MOD-1112',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-8',
    componentCategory: 'PLATELETS',
    currentTemperatureCelsius: 3.10,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.25,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0300,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T14:04:00.000Z',
    batteryLevelPercentage: 73,
    signalRssiDbm: -77,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000112',
  },
  {
    id: 'TEL-MODB-0113',
    sensorDeviceId: 'SENS-IOT-MOD-1113',
    storageUnitIdentifier: 'COLD-ROOM-ZONE-1',
    componentCategory: 'CRYOPRECIPITATE',
    currentTemperatureCelsius: 3.40,
    targetRangeMinCelsius: 2.0,
    targetRangeMaxCelsius: 6.0,
    meanKineticTemperature24h: 3.55,
    thermalExcursionDurationSeconds: 0,
    kineticDegradationIndex: 0.0450,
    complianceStatus: 'OPTIMAL',
    timestampIso: '2026-09-09T15:11:00.000Z',
    batteryLevelPercentage: 72,
    signalRssiDbm: -78,
    cryptographicTelemetrySignature: 'NIST-P256-SIG-TELEMETRY-000113',
  },
];

export function computeMeanKineticTemperature(tempsCelsius: number[], activationEnergyJoulePerMole = 83144): number {
  const R = 8.314472;
  const kelvinTemps = tempsCelsius.map(t => t + 273.15);
  const sumExp = kelvinTemps.reduce((acc, tk) => acc + Math.exp(-activationEnergyJoulePerMole / (R * tk)), 0);
  const avgExp = sumExp / tempsCelsius.length;
  const mktKelvin = -activationEnergyJoulePerMole / (R * Math.log(avgExp));
  return mktKelvin - 273.15;
}

export function evaluateColdChainCompliance(reading: ModbusChamberRecord): boolean {
  return reading.complianceStatus === 'OPTIMAL' || reading.complianceStatus === 'WARNING_TREND';
}
