/**
 * BloodBridge Immunology & Rare Blood Database — Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog
 * High-precision immunohematology, alloantibody identification, and rare phenotypes.
 */

export interface HighPrevalenceAntigenRecord {
  recordId: string;
  systemName: string;
  isbtNumber: number;
  antigenName: string;
  geneSymbol: string;
  chromosomeLocus: string;
  populationFrequencySubcontinentPercentage: number;
  clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS' | 'MODERATE_DELAYED_HEMOLYSIS' | 'BENIGN_NO_EFFECT';
  hspHdfnAssociation: boolean;
  antibodyOptimalTemperatureCelsius: number;
  immunoglobulinClass: 'IgG1' | 'IgG3' | 'IgG2' | 'IgM' | 'IgA';
  complementBindingCapacity: boolean;
  enzymeSensitivity: { ficin: 'DESTROYED' | 'ENHANCED' | 'UNAFFECTED'; dtt: 'DESTROYED' | 'RESISTANT' };
  emergencyMobilizationHotline: string;
  lastUpdatedRegistryDate: string;
}

export const EMMMAMPELHIGHPREVALENCE_REGISTRY_DATA: HighPrevalenceAntigenRecord[] = [
  {
    recordId: 'IMM-EMMM-0001',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #1',
    isbtNumber: 2,
    antigenName: 'Ag-EMM-001',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 2p11',
    populationFrequencySubcontinentPercentage: 0.991,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-001',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0002',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #2',
    isbtNumber: 3,
    antigenName: 'Ag-EMM-002',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 3p12',
    populationFrequencySubcontinentPercentage: 1.981,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-002',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0003',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #3',
    isbtNumber: 4,
    antigenName: 'Ag-EMM-003',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 4p13',
    populationFrequencySubcontinentPercentage: 2.971,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-003',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0004',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #4',
    isbtNumber: 5,
    antigenName: 'Ag-EMM-004',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 5p14',
    populationFrequencySubcontinentPercentage: 3.961,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-004',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0005',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #5',
    isbtNumber: 6,
    antigenName: 'Ag-EMM-005',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 6p15',
    populationFrequencySubcontinentPercentage: 4.951,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-005',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0006',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #6',
    isbtNumber: 7,
    antigenName: 'Ag-EMM-006',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 7p16',
    populationFrequencySubcontinentPercentage: 5.941,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-006',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0007',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #7',
    isbtNumber: 8,
    antigenName: 'Ag-EMM-007',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 8p17',
    populationFrequencySubcontinentPercentage: 6.931,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-007',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0008',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #8',
    isbtNumber: 9,
    antigenName: 'Ag-EMM-008',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 9p18',
    populationFrequencySubcontinentPercentage: 7.921,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-008',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0009',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #9',
    isbtNumber: 10,
    antigenName: 'Ag-EMM-009',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 10p19',
    populationFrequencySubcontinentPercentage: 8.911,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-009',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0010',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #10',
    isbtNumber: 11,
    antigenName: 'Ag-EMM-010',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 11p20',
    populationFrequencySubcontinentPercentage: 9.901,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-010',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0011',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #11',
    isbtNumber: 12,
    antigenName: 'Ag-EMM-011',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 12p21',
    populationFrequencySubcontinentPercentage: 10.891,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-011',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0012',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #12',
    isbtNumber: 13,
    antigenName: 'Ag-EMM-012',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 13p22',
    populationFrequencySubcontinentPercentage: 11.881,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-012',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0013',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #13',
    isbtNumber: 14,
    antigenName: 'Ag-EMM-013',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 14p23',
    populationFrequencySubcontinentPercentage: 12.871,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-013',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0014',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #14',
    isbtNumber: 15,
    antigenName: 'Ag-EMM-014',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 15p24',
    populationFrequencySubcontinentPercentage: 13.861,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-014',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0015',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #15',
    isbtNumber: 16,
    antigenName: 'Ag-EMM-015',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 16p25',
    populationFrequencySubcontinentPercentage: 14.851,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-015',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0016',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #16',
    isbtNumber: 17,
    antigenName: 'Ag-EMM-016',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 17p26',
    populationFrequencySubcontinentPercentage: 15.841,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-016',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0017',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #17',
    isbtNumber: 18,
    antigenName: 'Ag-EMM-017',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 18p27',
    populationFrequencySubcontinentPercentage: 16.831,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-017',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0018',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #18',
    isbtNumber: 19,
    antigenName: 'Ag-EMM-018',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 19p28',
    populationFrequencySubcontinentPercentage: 17.821,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-018',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0019',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #19',
    isbtNumber: 20,
    antigenName: 'Ag-EMM-019',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 20p29',
    populationFrequencySubcontinentPercentage: 18.811,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-019',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0020',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #20',
    isbtNumber: 21,
    antigenName: 'Ag-EMM-020',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 21p10',
    populationFrequencySubcontinentPercentage: 19.801,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-020',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0021',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #21',
    isbtNumber: 22,
    antigenName: 'Ag-EMM-021',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 22p11',
    populationFrequencySubcontinentPercentage: 20.791,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-021',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0022',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #22',
    isbtNumber: 23,
    antigenName: 'Ag-EMM-022',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 1p12',
    populationFrequencySubcontinentPercentage: 21.781,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-022',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0023',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #23',
    isbtNumber: 24,
    antigenName: 'Ag-EMM-023',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 2p13',
    populationFrequencySubcontinentPercentage: 22.771,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-023',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0024',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #24',
    isbtNumber: 25,
    antigenName: 'Ag-EMM-024',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 3p14',
    populationFrequencySubcontinentPercentage: 23.761,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-024',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0025',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #25',
    isbtNumber: 26,
    antigenName: 'Ag-EMM-025',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 4p15',
    populationFrequencySubcontinentPercentage: 24.751,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-025',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0026',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #26',
    isbtNumber: 27,
    antigenName: 'Ag-EMM-026',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 5p16',
    populationFrequencySubcontinentPercentage: 25.741,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-026',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0027',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #27',
    isbtNumber: 28,
    antigenName: 'Ag-EMM-027',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 6p17',
    populationFrequencySubcontinentPercentage: 26.731,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-027',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0028',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #28',
    isbtNumber: 29,
    antigenName: 'Ag-EMM-028',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 7p18',
    populationFrequencySubcontinentPercentage: 27.721,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-028',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0029',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #29',
    isbtNumber: 30,
    antigenName: 'Ag-EMM-029',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 8p19',
    populationFrequencySubcontinentPercentage: 28.711,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-029',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0030',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #30',
    isbtNumber: 31,
    antigenName: 'Ag-EMM-030',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 9p20',
    populationFrequencySubcontinentPercentage: 29.701,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-030',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0031',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #31',
    isbtNumber: 32,
    antigenName: 'Ag-EMM-031',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 10p21',
    populationFrequencySubcontinentPercentage: 30.691,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-031',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0032',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #32',
    isbtNumber: 33,
    antigenName: 'Ag-EMM-032',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 11p22',
    populationFrequencySubcontinentPercentage: 31.681,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-032',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0033',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #33',
    isbtNumber: 34,
    antigenName: 'Ag-EMM-033',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 12p23',
    populationFrequencySubcontinentPercentage: 32.671,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-033',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0034',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #34',
    isbtNumber: 35,
    antigenName: 'Ag-EMM-034',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 13p24',
    populationFrequencySubcontinentPercentage: 33.661,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-034',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0035',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #35',
    isbtNumber: 36,
    antigenName: 'Ag-EMM-035',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 14p25',
    populationFrequencySubcontinentPercentage: 34.651,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-035',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0036',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #36',
    isbtNumber: 37,
    antigenName: 'Ag-EMM-036',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 15p26',
    populationFrequencySubcontinentPercentage: 35.641,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-036',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0037',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #37',
    isbtNumber: 38,
    antigenName: 'Ag-EMM-037',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 16p27',
    populationFrequencySubcontinentPercentage: 36.631,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-037',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0038',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #38',
    isbtNumber: 39,
    antigenName: 'Ag-EMM-038',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 17p28',
    populationFrequencySubcontinentPercentage: 37.621,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-038',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0039',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #39',
    isbtNumber: 40,
    antigenName: 'Ag-EMM-039',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 18p29',
    populationFrequencySubcontinentPercentage: 38.611,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-039',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0040',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #40',
    isbtNumber: 41,
    antigenName: 'Ag-EMM-040',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 19p10',
    populationFrequencySubcontinentPercentage: 39.601,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-040',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0041',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #41',
    isbtNumber: 42,
    antigenName: 'Ag-EMM-041',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 20p11',
    populationFrequencySubcontinentPercentage: 40.591,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-041',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0042',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #42',
    isbtNumber: 43,
    antigenName: 'Ag-EMM-042',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 21p12',
    populationFrequencySubcontinentPercentage: 41.581,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-042',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0043',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #43',
    isbtNumber: 44,
    antigenName: 'Ag-EMM-043',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 22p13',
    populationFrequencySubcontinentPercentage: 42.571,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-043',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0044',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #44',
    isbtNumber: 1,
    antigenName: 'Ag-EMM-044',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 1p14',
    populationFrequencySubcontinentPercentage: 43.561,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-044',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0045',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #45',
    isbtNumber: 2,
    antigenName: 'Ag-EMM-045',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 2p15',
    populationFrequencySubcontinentPercentage: 44.551,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-045',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0046',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #46',
    isbtNumber: 3,
    antigenName: 'Ag-EMM-046',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 3p16',
    populationFrequencySubcontinentPercentage: 45.541,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-046',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0047',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #47',
    isbtNumber: 4,
    antigenName: 'Ag-EMM-047',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 4p17',
    populationFrequencySubcontinentPercentage: 46.531,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-047',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0048',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #48',
    isbtNumber: 5,
    antigenName: 'Ag-EMM-048',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 5p18',
    populationFrequencySubcontinentPercentage: 47.521,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-048',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0049',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #49',
    isbtNumber: 6,
    antigenName: 'Ag-EMM-049',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 6p19',
    populationFrequencySubcontinentPercentage: 48.511,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-049',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0050',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #50',
    isbtNumber: 7,
    antigenName: 'Ag-EMM-050',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 7p20',
    populationFrequencySubcontinentPercentage: 49.501,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-050',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0051',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #51',
    isbtNumber: 8,
    antigenName: 'Ag-EMM-051',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 8p21',
    populationFrequencySubcontinentPercentage: 50.491,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-051',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0052',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #52',
    isbtNumber: 9,
    antigenName: 'Ag-EMM-052',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 9p22',
    populationFrequencySubcontinentPercentage: 51.481,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-052',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0053',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #53',
    isbtNumber: 10,
    antigenName: 'Ag-EMM-053',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 10p23',
    populationFrequencySubcontinentPercentage: 52.471,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-053',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0054',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #54',
    isbtNumber: 11,
    antigenName: 'Ag-EMM-054',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 11p24',
    populationFrequencySubcontinentPercentage: 53.461,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-054',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0055',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #55',
    isbtNumber: 12,
    antigenName: 'Ag-EMM-055',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 12p25',
    populationFrequencySubcontinentPercentage: 54.451,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-055',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0056',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #56',
    isbtNumber: 13,
    antigenName: 'Ag-EMM-056',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 13p26',
    populationFrequencySubcontinentPercentage: 55.441,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-056',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0057',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #57',
    isbtNumber: 14,
    antigenName: 'Ag-EMM-057',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 14p27',
    populationFrequencySubcontinentPercentage: 56.431,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-057',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0058',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #58',
    isbtNumber: 15,
    antigenName: 'Ag-EMM-058',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 15p28',
    populationFrequencySubcontinentPercentage: 57.421,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-058',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0059',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #59',
    isbtNumber: 16,
    antigenName: 'Ag-EMM-059',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 16p29',
    populationFrequencySubcontinentPercentage: 58.411,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-059',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0060',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #60',
    isbtNumber: 17,
    antigenName: 'Ag-EMM-060',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 17p10',
    populationFrequencySubcontinentPercentage: 59.401,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-060',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0061',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #61',
    isbtNumber: 18,
    antigenName: 'Ag-EMM-061',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 18p11',
    populationFrequencySubcontinentPercentage: 60.391,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-061',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0062',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #62',
    isbtNumber: 19,
    antigenName: 'Ag-EMM-062',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 19p12',
    populationFrequencySubcontinentPercentage: 61.381,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-062',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0063',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #63',
    isbtNumber: 20,
    antigenName: 'Ag-EMM-063',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 20p13',
    populationFrequencySubcontinentPercentage: 62.371,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-063',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0064',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #64',
    isbtNumber: 21,
    antigenName: 'Ag-EMM-064',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 21p14',
    populationFrequencySubcontinentPercentage: 63.361,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-064',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0065',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #65',
    isbtNumber: 22,
    antigenName: 'Ag-EMM-065',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 22p15',
    populationFrequencySubcontinentPercentage: 64.351,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-065',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0066',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #66',
    isbtNumber: 23,
    antigenName: 'Ag-EMM-066',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 1p16',
    populationFrequencySubcontinentPercentage: 65.341,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-066',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0067',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #67',
    isbtNumber: 24,
    antigenName: 'Ag-EMM-067',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 2p17',
    populationFrequencySubcontinentPercentage: 66.331,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-067',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0068',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #68',
    isbtNumber: 25,
    antigenName: 'Ag-EMM-068',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 3p18',
    populationFrequencySubcontinentPercentage: 67.321,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-068',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0069',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #69',
    isbtNumber: 26,
    antigenName: 'Ag-EMM-069',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 4p19',
    populationFrequencySubcontinentPercentage: 68.311,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-069',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0070',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #70',
    isbtNumber: 27,
    antigenName: 'Ag-EMM-070',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 5p20',
    populationFrequencySubcontinentPercentage: 69.301,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-070',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0071',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #71',
    isbtNumber: 28,
    antigenName: 'Ag-EMM-071',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 6p21',
    populationFrequencySubcontinentPercentage: 70.291,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-071',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0072',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #72',
    isbtNumber: 29,
    antigenName: 'Ag-EMM-072',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 7p22',
    populationFrequencySubcontinentPercentage: 71.281,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-072',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0073',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #73',
    isbtNumber: 30,
    antigenName: 'Ag-EMM-073',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 8p23',
    populationFrequencySubcontinentPercentage: 72.271,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-073',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0074',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #74',
    isbtNumber: 31,
    antigenName: 'Ag-EMM-074',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 9p24',
    populationFrequencySubcontinentPercentage: 73.261,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-074',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0075',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #75',
    isbtNumber: 32,
    antigenName: 'Ag-EMM-075',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 10p25',
    populationFrequencySubcontinentPercentage: 74.251,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-075',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0076',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #76',
    isbtNumber: 33,
    antigenName: 'Ag-EMM-076',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 11p26',
    populationFrequencySubcontinentPercentage: 75.241,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-076',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0077',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #77',
    isbtNumber: 34,
    antigenName: 'Ag-EMM-077',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 12p27',
    populationFrequencySubcontinentPercentage: 76.231,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-077',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0078',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #78',
    isbtNumber: 35,
    antigenName: 'Ag-EMM-078',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 13p28',
    populationFrequencySubcontinentPercentage: 77.221,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-078',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0079',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #79',
    isbtNumber: 36,
    antigenName: 'Ag-EMM-079',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 14p29',
    populationFrequencySubcontinentPercentage: 78.211,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-079',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0080',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #80',
    isbtNumber: 37,
    antigenName: 'Ag-EMM-080',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 15p10',
    populationFrequencySubcontinentPercentage: 79.201,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-080',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0081',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #81',
    isbtNumber: 38,
    antigenName: 'Ag-EMM-081',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 16p11',
    populationFrequencySubcontinentPercentage: 80.191,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-081',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0082',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #82',
    isbtNumber: 39,
    antigenName: 'Ag-EMM-082',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 17p12',
    populationFrequencySubcontinentPercentage: 81.181,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-082',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0083',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #83',
    isbtNumber: 40,
    antigenName: 'Ag-EMM-083',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 18p13',
    populationFrequencySubcontinentPercentage: 82.171,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-083',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0084',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #84',
    isbtNumber: 41,
    antigenName: 'Ag-EMM-084',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 19p14',
    populationFrequencySubcontinentPercentage: 83.161,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-084',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0085',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #85',
    isbtNumber: 42,
    antigenName: 'Ag-EMM-085',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 20p15',
    populationFrequencySubcontinentPercentage: 84.151,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-085',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0086',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #86',
    isbtNumber: 43,
    antigenName: 'Ag-EMM-086',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 21p16',
    populationFrequencySubcontinentPercentage: 85.141,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgG3',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-086',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0087',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #87',
    isbtNumber: 44,
    antigenName: 'Ag-EMM-087',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 22p17',
    populationFrequencySubcontinentPercentage: 86.131,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG2',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-087',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0088',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #88',
    isbtNumber: 1,
    antigenName: 'Ag-EMM-088',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 1p18',
    populationFrequencySubcontinentPercentage: 87.121,
    clinicalSignificanceInTransfusion: 'MODERATE_DELAYED_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgM',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'ENHANCED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-088',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0089',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #89',
    isbtNumber: 2,
    antigenName: 'Ag-EMM-089',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 2p19',
    populationFrequencySubcontinentPercentage: 88.111,
    clinicalSignificanceInTransfusion: 'BENIGN_NO_EFFECT',
    hspHdfnAssociation: true,
    antibodyOptimalTemperatureCelsius: 37,
    immunoglobulinClass: 'IgA',
    complementBindingCapacity: false,
    enzymeSensitivity: {
      ficin: 'UNAFFECTED',
      dtt: 'RESISTANT'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-089',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
  {
    recordId: 'IMM-EMMM-0090',
    systemName: 'Emm, MAM, and PEL High-Prevalence Antigen Deficiency Catalog System - Variant #90',
    isbtNumber: 3,
    antigenName: 'Ag-EMM-090',
    geneSymbol: 'GENE-EMMM',
    chromosomeLocus: 'Chr 3p20',
    populationFrequencySubcontinentPercentage: 89.101,
    clinicalSignificanceInTransfusion: 'HIGH_ACUTE_HEMOLYSIS',
    hspHdfnAssociation: false,
    antibodyOptimalTemperatureCelsius: 4,
    immunoglobulinClass: 'IgG1',
    complementBindingCapacity: true,
    enzymeSensitivity: {
      ficin: 'DESTROYED',
      dtt: 'DESTROYED'
    },
    emergencyMobilizationHotline: '+91-800-BLOOD-RARE-090',
    lastUpdatedRegistryDate: '2026-09-09T00:00:00.000Z',
  },
];

export function isAntigenClinicallySignificant(antigen: HighPrevalenceAntigenRecord): boolean {
  return antigen.clinicalSignificanceInTransfusion === 'HIGH_ACUTE_HEMOLYSIS' || antigen.hspHdfnAssociation;
}

export function getRareDonorsByFrequency(thresholdPercent = 0.01): HighPrevalenceAntigenRecord[] {
  return EMMMAMPELHIGHPREVALENCE_REGISTRY_DATA.filter(item => item.populationFrequencySubcontinentPercentage <= thresholdPercent);
}
