/**
 * BloodBridge Geo Registry — Andhra Pradesh — Visakhapatnam & Coastal Belt
 * Licensed blood banks, trauma centers, and cold chain distribution hubs.
 */

export interface BloodBankFacilityRecord {
  id: string;
  facilityName: string;
  licenseNumber: string;
  stateRegion: string;
  districtCity: string;
  latitude: number;
  longitude: number;
  category: 'GOVERNMENT_MEDICAL_COLLEGE' | 'RED_CROSS_REGIONAL' | 'PRIVATE_TERTIARY' | 'DEFENCE_MILITARY' | 'CHARITABLE_TRUST';
  componentSeparationLicensed: boolean;
  apheresisAvailable: boolean;
  natTestingAvailable: boolean;
  refrigeratedCentrifugeUnits: number;
  deepFreezersMinus80Count: number;
  plateletAgitatorsCount: number;
  averageMonthlyCollectionUnits: number;
  emergencyContactPhone: string;
  nodalTransfusionOfficer: string;
  operatingHours: string;
  greenCorridorDispatchEnabled: boolean;
  backupGeneratorCapacityKva: number;
}

export const ANDHRAPRADESHVISAKHAPATNAM_FACILITIES: BloodBankFacilityRecord[] = [
  {
    id: 'FAC-ANDH-0001',
    facilityName: 'Andhra Pradesh Blood Center #1 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0001',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.646800,
    longitude: 83.208500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2001-8001',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #1',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0002',
    facilityName: 'Andhra Pradesh Blood Center #2 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0002',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.731800,
    longitude: 83.323500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2002-8002',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #2',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0003',
    facilityName: 'Andhra Pradesh Blood Center #3 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0003',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.566800,
    longitude: 83.188500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2003-8003',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #3',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0004',
    facilityName: 'Andhra Pradesh Blood Center #4 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0004',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.651800,
    longitude: 83.303500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2004-8004',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #4',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0005',
    facilityName: 'Andhra Pradesh Blood Center #5 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0005',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.736800,
    longitude: 83.168500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2005-8005',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #5',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0006',
    facilityName: 'Andhra Pradesh Blood Center #6 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0006',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.571800,
    longitude: 83.283500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2006-8006',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #6',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0007',
    facilityName: 'Andhra Pradesh Blood Center #7 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0007',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.656800,
    longitude: 83.148500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2007-8007',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #7',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0008',
    facilityName: 'Andhra Pradesh Blood Center #8 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0008',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.741800,
    longitude: 83.263500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2008-8008',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #8',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0009',
    facilityName: 'Andhra Pradesh Blood Center #9 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0009',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.576800,
    longitude: 83.128500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2009-8009',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #9',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0010',
    facilityName: 'Andhra Pradesh Blood Center #10 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0010',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.661800,
    longitude: 83.243500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2010-8010',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #10',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0011',
    facilityName: 'Andhra Pradesh Blood Center #11 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0011',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.746800,
    longitude: 83.108500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2011-8011',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #11',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0012',
    facilityName: 'Andhra Pradesh Blood Center #12 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0012',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.581800,
    longitude: 83.223500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2012-8012',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #12',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0013',
    facilityName: 'Andhra Pradesh Blood Center #13 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0013',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.666800,
    longitude: 83.338500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2013-8013',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #13',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0014',
    facilityName: 'Andhra Pradesh Blood Center #14 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0014',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.751800,
    longitude: 83.203500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2014-8014',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #14',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0015',
    facilityName: 'Andhra Pradesh Blood Center #15 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0015',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.586800,
    longitude: 83.318500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2015-8015',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #15',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0016',
    facilityName: 'Andhra Pradesh Blood Center #16 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0016',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.671800,
    longitude: 83.183500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2016-8016',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #16',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0017',
    facilityName: 'Andhra Pradesh Blood Center #17 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0017',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.756800,
    longitude: 83.298500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2017-8017',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #17',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0018',
    facilityName: 'Andhra Pradesh Blood Center #18 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0018',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.591800,
    longitude: 83.163500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2018-8018',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #18',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0019',
    facilityName: 'Andhra Pradesh Blood Center #19 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0019',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.676800,
    longitude: 83.278500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2019-8019',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #19',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0020',
    facilityName: 'Andhra Pradesh Blood Center #20 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0020',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.761800,
    longitude: 83.143500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2020-8020',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #20',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0021',
    facilityName: 'Andhra Pradesh Blood Center #21 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0021',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.596800,
    longitude: 83.258500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2021-8021',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #21',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0022',
    facilityName: 'Andhra Pradesh Blood Center #22 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0022',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.681800,
    longitude: 83.123500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2022-8022',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #22',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0023',
    facilityName: 'Andhra Pradesh Blood Center #23 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0023',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.766800,
    longitude: 83.238500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2023-8023',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #23',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0024',
    facilityName: 'Andhra Pradesh Blood Center #24 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0024',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.601800,
    longitude: 83.103500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2024-8024',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #24',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0025',
    facilityName: 'Andhra Pradesh Blood Center #25 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0025',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.686800,
    longitude: 83.218500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2025-8025',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #25',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0026',
    facilityName: 'Andhra Pradesh Blood Center #26 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0026',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.771800,
    longitude: 83.333500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2026-8026',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #26',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0027',
    facilityName: 'Andhra Pradesh Blood Center #27 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0027',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.606800,
    longitude: 83.198500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2027-8027',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #27',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0028',
    facilityName: 'Andhra Pradesh Blood Center #28 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0028',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.691800,
    longitude: 83.313500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2028-8028',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #28',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0029',
    facilityName: 'Andhra Pradesh Blood Center #29 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0029',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.776800,
    longitude: 83.178500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2029-8029',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #29',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0030',
    facilityName: 'Andhra Pradesh Blood Center #30 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0030',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.611800,
    longitude: 83.293500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2030-8030',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #30',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0031',
    facilityName: 'Andhra Pradesh Blood Center #31 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0031',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.696800,
    longitude: 83.158500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2031-8031',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #31',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0032',
    facilityName: 'Andhra Pradesh Blood Center #32 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0032',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.781800,
    longitude: 83.273500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2032-8032',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #32',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0033',
    facilityName: 'Andhra Pradesh Blood Center #33 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0033',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.616800,
    longitude: 83.138500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2033-8033',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #33',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0034',
    facilityName: 'Andhra Pradesh Blood Center #34 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0034',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.701800,
    longitude: 83.253500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2034-8034',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #34',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0035',
    facilityName: 'Andhra Pradesh Blood Center #35 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0035',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.786800,
    longitude: 83.118500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2035-8035',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #35',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0036',
    facilityName: 'Andhra Pradesh Blood Center #36 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0036',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.621800,
    longitude: 83.233500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2036-8036',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #36',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0037',
    facilityName: 'Andhra Pradesh Blood Center #37 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0037',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.706800,
    longitude: 83.098500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2037-8037',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #37',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0038',
    facilityName: 'Andhra Pradesh Blood Center #38 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0038',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.791800,
    longitude: 83.213500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2038-8038',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #38',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0039',
    facilityName: 'Andhra Pradesh Blood Center #39 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0039',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.626800,
    longitude: 83.328500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2039-8039',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #39',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0040',
    facilityName: 'Andhra Pradesh Blood Center #40 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0040',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.711800,
    longitude: 83.193500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2040-8040',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #40',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0041',
    facilityName: 'Andhra Pradesh Blood Center #41 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0041',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.796800,
    longitude: 83.308500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2041-8041',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #41',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0042',
    facilityName: 'Andhra Pradesh Blood Center #42 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0042',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.631800,
    longitude: 83.173500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2042-8042',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #42',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0043',
    facilityName: 'Andhra Pradesh Blood Center #43 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0043',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.716800,
    longitude: 83.288500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2043-8043',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #43',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0044',
    facilityName: 'Andhra Pradesh Blood Center #44 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0044',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.801800,
    longitude: 83.153500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2044-8044',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #44',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0045',
    facilityName: 'Andhra Pradesh Blood Center #45 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0045',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.636800,
    longitude: 83.268500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2045-8045',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #45',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0046',
    facilityName: 'Andhra Pradesh Blood Center #46 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0046',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.721800,
    longitude: 83.133500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2046-8046',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #46',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0047',
    facilityName: 'Andhra Pradesh Blood Center #47 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0047',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.806800,
    longitude: 83.248500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2047-8047',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #47',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0048',
    facilityName: 'Andhra Pradesh Blood Center #48 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0048',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.641800,
    longitude: 83.113500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2048-8048',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #48',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0049',
    facilityName: 'Andhra Pradesh Blood Center #49 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0049',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.726800,
    longitude: 83.228500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2049-8049',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #49',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0050',
    facilityName: 'Andhra Pradesh Blood Center #50 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0050',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.561800,
    longitude: 83.093500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2050-8050',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #50',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0051',
    facilityName: 'Andhra Pradesh Blood Center #51 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0051',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.646800,
    longitude: 83.208500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2051-8051',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #51',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0052',
    facilityName: 'Andhra Pradesh Blood Center #52 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0052',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.731800,
    longitude: 83.323500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2052-8052',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #52',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0053',
    facilityName: 'Andhra Pradesh Blood Center #53 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0053',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.566800,
    longitude: 83.188500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2053-8053',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #53',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0054',
    facilityName: 'Andhra Pradesh Blood Center #54 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0054',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.651800,
    longitude: 83.303500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2054-8054',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #54',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0055',
    facilityName: 'Andhra Pradesh Blood Center #55 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0055',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.736800,
    longitude: 83.168500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2055-8055',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #55',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0056',
    facilityName: 'Andhra Pradesh Blood Center #56 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0056',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.571800,
    longitude: 83.283500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2056-8056',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #56',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0057',
    facilityName: 'Andhra Pradesh Blood Center #57 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0057',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.656800,
    longitude: 83.148500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2057-8057',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #57',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0058',
    facilityName: 'Andhra Pradesh Blood Center #58 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0058',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.741800,
    longitude: 83.263500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2058-8058',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #58',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0059',
    facilityName: 'Andhra Pradesh Blood Center #59 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0059',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.576800,
    longitude: 83.128500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2059-8059',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #59',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0060',
    facilityName: 'Andhra Pradesh Blood Center #60 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0060',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.661800,
    longitude: 83.243500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2060-8060',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #60',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0061',
    facilityName: 'Andhra Pradesh Blood Center #61 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0061',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.746800,
    longitude: 83.108500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2061-8061',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #61',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0062',
    facilityName: 'Andhra Pradesh Blood Center #62 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0062',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.581800,
    longitude: 83.223500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2062-8062',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #62',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0063',
    facilityName: 'Andhra Pradesh Blood Center #63 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0063',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.666800,
    longitude: 83.338500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2063-8063',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #63',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0064',
    facilityName: 'Andhra Pradesh Blood Center #64 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0064',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.751800,
    longitude: 83.203500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2064-8064',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #64',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0065',
    facilityName: 'Andhra Pradesh Blood Center #65 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0065',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.586800,
    longitude: 83.318500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2065-8065',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #65',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0066',
    facilityName: 'Andhra Pradesh Blood Center #66 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0066',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.671800,
    longitude: 83.183500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2066-8066',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #66',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0067',
    facilityName: 'Andhra Pradesh Blood Center #67 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0067',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.756800,
    longitude: 83.298500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2067-8067',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #67',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0068',
    facilityName: 'Andhra Pradesh Blood Center #68 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0068',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.591800,
    longitude: 83.163500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2068-8068',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #68',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0069',
    facilityName: 'Andhra Pradesh Blood Center #69 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0069',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.676800,
    longitude: 83.278500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2069-8069',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #69',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0070',
    facilityName: 'Andhra Pradesh Blood Center #70 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0070',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.761800,
    longitude: 83.143500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2070-8070',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #70',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0071',
    facilityName: 'Andhra Pradesh Blood Center #71 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0071',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.596800,
    longitude: 83.258500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2071-8071',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #71',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0072',
    facilityName: 'Andhra Pradesh Blood Center #72 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0072',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.681800,
    longitude: 83.123500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2072-8072',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #72',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0073',
    facilityName: 'Andhra Pradesh Blood Center #73 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0073',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.766800,
    longitude: 83.238500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2073-8073',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #73',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0074',
    facilityName: 'Andhra Pradesh Blood Center #74 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0074',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.601800,
    longitude: 83.103500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2074-8074',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #74',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0075',
    facilityName: 'Andhra Pradesh Blood Center #75 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0075',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.686800,
    longitude: 83.218500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2075-8075',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #75',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0076',
    facilityName: 'Andhra Pradesh Blood Center #76 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0076',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.771800,
    longitude: 83.333500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2076-8076',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #76',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0077',
    facilityName: 'Andhra Pradesh Blood Center #77 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0077',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.606800,
    longitude: 83.198500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2077-8077',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #77',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0078',
    facilityName: 'Andhra Pradesh Blood Center #78 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0078',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.691800,
    longitude: 83.313500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2078-8078',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #78',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0079',
    facilityName: 'Andhra Pradesh Blood Center #79 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0079',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.776800,
    longitude: 83.178500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2079-8079',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #79',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0080',
    facilityName: 'Andhra Pradesh Blood Center #80 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0080',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.611800,
    longitude: 83.293500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2080-8080',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #80',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0081',
    facilityName: 'Andhra Pradesh Blood Center #81 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0081',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.696800,
    longitude: 83.158500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2081-8081',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #81',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0082',
    facilityName: 'Andhra Pradesh Blood Center #82 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0082',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.781800,
    longitude: 83.273500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2082-8082',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #82',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0083',
    facilityName: 'Andhra Pradesh Blood Center #83 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0083',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.616800,
    longitude: 83.138500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2083-8083',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #83',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0084',
    facilityName: 'Andhra Pradesh Blood Center #84 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0084',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.701800,
    longitude: 83.253500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2084-8084',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #84',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0085',
    facilityName: 'Andhra Pradesh Blood Center #85 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0085',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.786800,
    longitude: 83.118500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2085-8085',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #85',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0086',
    facilityName: 'Andhra Pradesh Blood Center #86 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0086',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.621800,
    longitude: 83.233500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2086-8086',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #86',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0087',
    facilityName: 'Andhra Pradesh Blood Center #87 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0087',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.706800,
    longitude: 83.098500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2087-8087',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #87',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0088',
    facilityName: 'Andhra Pradesh Blood Center #88 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0088',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.791800,
    longitude: 83.213500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2088-8088',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #88',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0089',
    facilityName: 'Andhra Pradesh Blood Center #89 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0089',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.626800,
    longitude: 83.328500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2089-8089',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #89',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0090',
    facilityName: 'Andhra Pradesh Blood Center #90 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0090',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.711800,
    longitude: 83.193500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2090-8090',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #90',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0091',
    facilityName: 'Andhra Pradesh Blood Center #91 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0091',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.796800,
    longitude: 83.308500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2091-8091',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #91',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0092',
    facilityName: 'Andhra Pradesh Blood Center #92 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0092',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.631800,
    longitude: 83.173500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2092-8092',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #92',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0093',
    facilityName: 'Andhra Pradesh Blood Center #93 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0093',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.716800,
    longitude: 83.288500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2093-8093',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #93',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0094',
    facilityName: 'Andhra Pradesh Blood Center #94 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0094',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.801800,
    longitude: 83.153500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2094-8094',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #94',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0095',
    facilityName: 'Andhra Pradesh Blood Center #95 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0095',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.636800,
    longitude: 83.268500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2095-8095',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #95',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0096',
    facilityName: 'Andhra Pradesh Blood Center #96 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0096',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.721800,
    longitude: 83.133500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2096-8096',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #96',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0097',
    facilityName: 'Andhra Pradesh Blood Center #97 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0097',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.806800,
    longitude: 83.248500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2097-8097',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #97',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0098',
    facilityName: 'Andhra Pradesh Blood Center #98 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0098',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.641800,
    longitude: 83.113500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2098-8098',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #98',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0099',
    facilityName: 'Andhra Pradesh Blood Center #99 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0099',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.726800,
    longitude: 83.228500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2099-8099',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #99',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0100',
    facilityName: 'Andhra Pradesh Blood Center #100 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0100',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.561800,
    longitude: 83.093500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2100-8100',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #100',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0101',
    facilityName: 'Andhra Pradesh Blood Center #101 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0101',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.646800,
    longitude: 83.208500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2101-8101',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #101',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0102',
    facilityName: 'Andhra Pradesh Blood Center #102 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0102',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.731800,
    longitude: 83.323500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2102-8102',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #102',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0103',
    facilityName: 'Andhra Pradesh Blood Center #103 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0103',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.566800,
    longitude: 83.188500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2103-8103',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #103',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0104',
    facilityName: 'Andhra Pradesh Blood Center #104 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0104',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.651800,
    longitude: 83.303500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2104-8104',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #104',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0105',
    facilityName: 'Andhra Pradesh Blood Center #105 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0105',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.736800,
    longitude: 83.168500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2105-8105',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #105',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0106',
    facilityName: 'Andhra Pradesh Blood Center #106 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0106',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.571800,
    longitude: 83.283500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2106-8106',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #106',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0107',
    facilityName: 'Andhra Pradesh Blood Center #107 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0107',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.656800,
    longitude: 83.148500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2107-8107',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #107',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0108',
    facilityName: 'Andhra Pradesh Blood Center #108 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2020/0108',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 17.741800,
    longitude: 83.263500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2108-8108',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #108',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ANDH-0109',
    facilityName: 'Andhra Pradesh Blood Center #109 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2021/0109',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 17.576800,
    longitude: 83.128500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2109-8109',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #109',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ANDH-0110',
    facilityName: 'Andhra Pradesh Blood Center #110 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2022/0110',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 17.661800,
    longitude: 83.243500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2110-8110',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #110',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ANDH-0111',
    facilityName: 'Andhra Pradesh Blood Center #111 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2023/0111',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 17.746800,
    longitude: 83.108500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2111-8111',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #111',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ANDH-0112',
    facilityName: 'Andhra Pradesh Blood Center #112 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2024/0112',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 17.581800,
    longitude: 83.223500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2112-8112',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #112',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ANDH-0113',
    facilityName: 'Andhra Pradesh Blood Center #113 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-AND-2025/0113',
    stateRegion: 'Andhra Pradesh — Visakhapatnam & Coastal Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 17.666800,
    longitude: 83.338500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2113-8113',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Andh #113',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
];

export function getAndhraPradeshVisakhapatnamFacilityById(id: string): BloodBankFacilityRecord | undefined {
  return ANDHRAPRADESHVISAKHAPATNAM_FACILITIES.find(f => f.id === id);
}

export function calculateHaversineDistanceKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371;
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a = Math.sin(dLat/2) * Math.sin(dLat/2) + Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLon/2) * Math.sin(dLon/2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
  return R * c;
}
