/**
 * BloodBridge Geo Registry — Gujarat — Ahmedabad & Gandhinagar Belt
 * Licensed blood banks, trauma centers, and cold chain distribution hubs.
 */

export interface BloodBankFacilityRecord {
  id: string;
  facilityName: string;
  licenseNumber: string;
  stateRegion: string;
  districtCity: string;
  latitude: number;
  longitude: number;
  category: 'GOVERNMENT_MEDICAL_COLLEGE' | 'RED_CROSS_REGIONAL' | 'PRIVATE_TERTIARY' | 'DEFENCE_MILITARY' | 'CHARITABLE_TRUST';
  componentSeparationLicensed: boolean;
  apheresisAvailable: boolean;
  natTestingAvailable: boolean;
  refrigeratedCentrifugeUnits: number;
  deepFreezersMinus80Count: number;
  plateletAgitatorsCount: number;
  averageMonthlyCollectionUnits: number;
  emergencyContactPhone: string;
  nodalTransfusionOfficer: string;
  operatingHours: string;
  greenCorridorDispatchEnabled: boolean;
  backupGeneratorCapacityKva: number;
}

export const GUJARATAHMEDABAD_FACILITIES: BloodBankFacilityRecord[] = [
  {
    id: 'FAC-GUJA-0001',
    facilityName: 'Gujarat Blood Center #1 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0001',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 22.982500,
    longitude: 72.561400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2001-8001',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #1',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0002',
    facilityName: 'Gujarat Blood Center #2 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0002',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 23.067500,
    longitude: 72.676400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2002-8002',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #2',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0003',
    facilityName: 'Gujarat Blood Center #3 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0003',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 22.902500,
    longitude: 72.541400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2003-8003',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #3',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0004',
    facilityName: 'Gujarat Blood Center #4 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0004',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 22.987500,
    longitude: 72.656400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2004-8004',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #4',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0005',
    facilityName: 'Gujarat Blood Center #5 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0005',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 23.072500,
    longitude: 72.521400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2005-8005',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #5',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0006',
    facilityName: 'Gujarat Blood Center #6 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0006',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 22.907500,
    longitude: 72.636400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2006-8006',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #6',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0007',
    facilityName: 'Gujarat Blood Center #7 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0007',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 22.992500,
    longitude: 72.501400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2007-8007',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #7',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0008',
    facilityName: 'Gujarat Blood Center #8 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0008',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 23.077500,
    longitude: 72.616400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2008-8008',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #8',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0009',
    facilityName: 'Gujarat Blood Center #9 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0009',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 22.912500,
    longitude: 72.481400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2009-8009',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #9',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0010',
    facilityName: 'Gujarat Blood Center #10 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0010',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 22.997500,
    longitude: 72.596400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2010-8010',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #10',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0011',
    facilityName: 'Gujarat Blood Center #11 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0011',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 23.082500,
    longitude: 72.461400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2011-8011',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #11',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0012',
    facilityName: 'Gujarat Blood Center #12 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0012',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 22.917500,
    longitude: 72.576400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2012-8012',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #12',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0013',
    facilityName: 'Gujarat Blood Center #13 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0013',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 23.002500,
    longitude: 72.691400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2013-8013',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #13',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0014',
    facilityName: 'Gujarat Blood Center #14 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0014',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 23.087500,
    longitude: 72.556400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2014-8014',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #14',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0015',
    facilityName: 'Gujarat Blood Center #15 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0015',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 22.922500,
    longitude: 72.671400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2015-8015',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #15',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0016',
    facilityName: 'Gujarat Blood Center #16 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0016',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 23.007500,
    longitude: 72.536400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2016-8016',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #16',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0017',
    facilityName: 'Gujarat Blood Center #17 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0017',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 23.092500,
    longitude: 72.651400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2017-8017',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #17',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0018',
    facilityName: 'Gujarat Blood Center #18 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0018',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 22.927500,
    longitude: 72.516400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2018-8018',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #18',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0019',
    facilityName: 'Gujarat Blood Center #19 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0019',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 23.012500,
    longitude: 72.631400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2019-8019',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #19',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0020',
    facilityName: 'Gujarat Blood Center #20 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0020',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 23.097500,
    longitude: 72.496400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2020-8020',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #20',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0021',
    facilityName: 'Gujarat Blood Center #21 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0021',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 22.932500,
    longitude: 72.611400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2021-8021',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #21',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0022',
    facilityName: 'Gujarat Blood Center #22 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0022',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 23.017500,
    longitude: 72.476400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2022-8022',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #22',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0023',
    facilityName: 'Gujarat Blood Center #23 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0023',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 23.102500,
    longitude: 72.591400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2023-8023',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #23',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0024',
    facilityName: 'Gujarat Blood Center #24 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0024',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 22.937500,
    longitude: 72.456400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2024-8024',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #24',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0025',
    facilityName: 'Gujarat Blood Center #25 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0025',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 23.022500,
    longitude: 72.571400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2025-8025',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #25',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0026',
    facilityName: 'Gujarat Blood Center #26 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0026',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 23.107500,
    longitude: 72.686400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2026-8026',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #26',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0027',
    facilityName: 'Gujarat Blood Center #27 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0027',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 22.942500,
    longitude: 72.551400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2027-8027',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #27',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0028',
    facilityName: 'Gujarat Blood Center #28 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0028',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 23.027500,
    longitude: 72.666400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2028-8028',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #28',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0029',
    facilityName: 'Gujarat Blood Center #29 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0029',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 23.112500,
    longitude: 72.531400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2029-8029',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #29',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0030',
    facilityName: 'Gujarat Blood Center #30 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0030',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 22.947500,
    longitude: 72.646400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2030-8030',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #30',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0031',
    facilityName: 'Gujarat Blood Center #31 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0031',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 23.032500,
    longitude: 72.511400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2031-8031',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #31',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0032',
    facilityName: 'Gujarat Blood Center #32 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0032',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 23.117500,
    longitude: 72.626400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2032-8032',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #32',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0033',
    facilityName: 'Gujarat Blood Center #33 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0033',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 22.952500,
    longitude: 72.491400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2033-8033',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #33',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0034',
    facilityName: 'Gujarat Blood Center #34 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0034',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 23.037500,
    longitude: 72.606400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2034-8034',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #34',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0035',
    facilityName: 'Gujarat Blood Center #35 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0035',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 23.122500,
    longitude: 72.471400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2035-8035',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #35',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0036',
    facilityName: 'Gujarat Blood Center #36 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0036',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 22.957500,
    longitude: 72.586400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2036-8036',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #36',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0037',
    facilityName: 'Gujarat Blood Center #37 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0037',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 23.042500,
    longitude: 72.451400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2037-8037',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #37',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0038',
    facilityName: 'Gujarat Blood Center #38 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0038',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 23.127500,
    longitude: 72.566400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2038-8038',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #38',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0039',
    facilityName: 'Gujarat Blood Center #39 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0039',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 22.962500,
    longitude: 72.681400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2039-8039',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #39',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0040',
    facilityName: 'Gujarat Blood Center #40 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0040',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 23.047500,
    longitude: 72.546400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2040-8040',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #40',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0041',
    facilityName: 'Gujarat Blood Center #41 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0041',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 23.132500,
    longitude: 72.661400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2041-8041',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #41',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0042',
    facilityName: 'Gujarat Blood Center #42 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0042',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 22.967500,
    longitude: 72.526400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2042-8042',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #42',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0043',
    facilityName: 'Gujarat Blood Center #43 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0043',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 23.052500,
    longitude: 72.641400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2043-8043',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #43',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0044',
    facilityName: 'Gujarat Blood Center #44 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0044',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 23.137500,
    longitude: 72.506400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2044-8044',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #44',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0045',
    facilityName: 'Gujarat Blood Center #45 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0045',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 22.972500,
    longitude: 72.621400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2045-8045',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #45',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0046',
    facilityName: 'Gujarat Blood Center #46 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0046',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 23.057500,
    longitude: 72.486400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2046-8046',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #46',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0047',
    facilityName: 'Gujarat Blood Center #47 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0047',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 23.142500,
    longitude: 72.601400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2047-8047',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #47',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0048',
    facilityName: 'Gujarat Blood Center #48 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0048',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 22.977500,
    longitude: 72.466400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2048-8048',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #48',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0049',
    facilityName: 'Gujarat Blood Center #49 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0049',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 23.062500,
    longitude: 72.581400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2049-8049',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #49',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0050',
    facilityName: 'Gujarat Blood Center #50 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0050',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 22.897500,
    longitude: 72.446400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2050-8050',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #50',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0051',
    facilityName: 'Gujarat Blood Center #51 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0051',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 22.982500,
    longitude: 72.561400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2051-8051',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #51',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0052',
    facilityName: 'Gujarat Blood Center #52 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0052',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 23.067500,
    longitude: 72.676400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2052-8052',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #52',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0053',
    facilityName: 'Gujarat Blood Center #53 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0053',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 22.902500,
    longitude: 72.541400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2053-8053',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #53',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0054',
    facilityName: 'Gujarat Blood Center #54 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0054',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 22.987500,
    longitude: 72.656400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2054-8054',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #54',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0055',
    facilityName: 'Gujarat Blood Center #55 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0055',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 23.072500,
    longitude: 72.521400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2055-8055',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #55',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0056',
    facilityName: 'Gujarat Blood Center #56 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0056',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 22.907500,
    longitude: 72.636400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2056-8056',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #56',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0057',
    facilityName: 'Gujarat Blood Center #57 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0057',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 22.992500,
    longitude: 72.501400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2057-8057',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #57',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0058',
    facilityName: 'Gujarat Blood Center #58 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0058',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 23.077500,
    longitude: 72.616400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2058-8058',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #58',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0059',
    facilityName: 'Gujarat Blood Center #59 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0059',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 22.912500,
    longitude: 72.481400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2059-8059',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #59',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0060',
    facilityName: 'Gujarat Blood Center #60 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0060',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 22.997500,
    longitude: 72.596400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2060-8060',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #60',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0061',
    facilityName: 'Gujarat Blood Center #61 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0061',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 23.082500,
    longitude: 72.461400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2061-8061',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #61',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0062',
    facilityName: 'Gujarat Blood Center #62 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0062',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 22.917500,
    longitude: 72.576400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2062-8062',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #62',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0063',
    facilityName: 'Gujarat Blood Center #63 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0063',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 23.002500,
    longitude: 72.691400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2063-8063',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #63',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0064',
    facilityName: 'Gujarat Blood Center #64 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0064',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 23.087500,
    longitude: 72.556400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2064-8064',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #64',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0065',
    facilityName: 'Gujarat Blood Center #65 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0065',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 22.922500,
    longitude: 72.671400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2065-8065',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #65',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0066',
    facilityName: 'Gujarat Blood Center #66 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0066',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 23.007500,
    longitude: 72.536400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2066-8066',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #66',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0067',
    facilityName: 'Gujarat Blood Center #67 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0067',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 23.092500,
    longitude: 72.651400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2067-8067',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #67',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0068',
    facilityName: 'Gujarat Blood Center #68 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0068',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 22.927500,
    longitude: 72.516400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2068-8068',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #68',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0069',
    facilityName: 'Gujarat Blood Center #69 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0069',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 23.012500,
    longitude: 72.631400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2069-8069',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #69',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0070',
    facilityName: 'Gujarat Blood Center #70 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0070',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 23.097500,
    longitude: 72.496400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2070-8070',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #70',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0071',
    facilityName: 'Gujarat Blood Center #71 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0071',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 22.932500,
    longitude: 72.611400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2071-8071',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #71',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0072',
    facilityName: 'Gujarat Blood Center #72 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0072',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 23.017500,
    longitude: 72.476400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2072-8072',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #72',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0073',
    facilityName: 'Gujarat Blood Center #73 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0073',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 23.102500,
    longitude: 72.591400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2073-8073',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #73',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0074',
    facilityName: 'Gujarat Blood Center #74 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0074',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 22.937500,
    longitude: 72.456400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2074-8074',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #74',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0075',
    facilityName: 'Gujarat Blood Center #75 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0075',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 23.022500,
    longitude: 72.571400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2075-8075',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #75',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0076',
    facilityName: 'Gujarat Blood Center #76 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0076',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 23.107500,
    longitude: 72.686400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2076-8076',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #76',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0077',
    facilityName: 'Gujarat Blood Center #77 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0077',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 22.942500,
    longitude: 72.551400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2077-8077',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #77',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0078',
    facilityName: 'Gujarat Blood Center #78 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0078',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 23.027500,
    longitude: 72.666400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2078-8078',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #78',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0079',
    facilityName: 'Gujarat Blood Center #79 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0079',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 23.112500,
    longitude: 72.531400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2079-8079',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #79',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0080',
    facilityName: 'Gujarat Blood Center #80 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0080',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 22.947500,
    longitude: 72.646400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2080-8080',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #80',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0081',
    facilityName: 'Gujarat Blood Center #81 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0081',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 23.032500,
    longitude: 72.511400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2081-8081',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #81',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0082',
    facilityName: 'Gujarat Blood Center #82 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0082',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 23.117500,
    longitude: 72.626400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2082-8082',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #82',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0083',
    facilityName: 'Gujarat Blood Center #83 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0083',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 22.952500,
    longitude: 72.491400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2083-8083',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #83',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0084',
    facilityName: 'Gujarat Blood Center #84 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0084',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 23.037500,
    longitude: 72.606400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2084-8084',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #84',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0085',
    facilityName: 'Gujarat Blood Center #85 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0085',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 23.122500,
    longitude: 72.471400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2085-8085',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #85',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0086',
    facilityName: 'Gujarat Blood Center #86 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0086',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 22.957500,
    longitude: 72.586400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2086-8086',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #86',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0087',
    facilityName: 'Gujarat Blood Center #87 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0087',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 23.042500,
    longitude: 72.451400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2087-8087',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #87',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0088',
    facilityName: 'Gujarat Blood Center #88 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0088',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 23.127500,
    longitude: 72.566400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2088-8088',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #88',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0089',
    facilityName: 'Gujarat Blood Center #89 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0089',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 22.962500,
    longitude: 72.681400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2089-8089',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #89',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0090',
    facilityName: 'Gujarat Blood Center #90 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0090',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 23.047500,
    longitude: 72.546400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2090-8090',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #90',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0091',
    facilityName: 'Gujarat Blood Center #91 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0091',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 23.132500,
    longitude: 72.661400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2091-8091',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #91',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0092',
    facilityName: 'Gujarat Blood Center #92 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0092',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 22.967500,
    longitude: 72.526400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2092-8092',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #92',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0093',
    facilityName: 'Gujarat Blood Center #93 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0093',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 23.052500,
    longitude: 72.641400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2093-8093',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #93',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0094',
    facilityName: 'Gujarat Blood Center #94 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0094',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 23.137500,
    longitude: 72.506400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2094-8094',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #94',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0095',
    facilityName: 'Gujarat Blood Center #95 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0095',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 22.972500,
    longitude: 72.621400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2095-8095',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #95',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0096',
    facilityName: 'Gujarat Blood Center #96 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0096',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 23.057500,
    longitude: 72.486400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2096-8096',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #96',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0097',
    facilityName: 'Gujarat Blood Center #97 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0097',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 23.142500,
    longitude: 72.601400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2097-8097',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #97',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0098',
    facilityName: 'Gujarat Blood Center #98 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0098',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 22.977500,
    longitude: 72.466400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2098-8098',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #98',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0099',
    facilityName: 'Gujarat Blood Center #99 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0099',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 23.062500,
    longitude: 72.581400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2099-8099',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #99',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0100',
    facilityName: 'Gujarat Blood Center #100 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0100',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 22.897500,
    longitude: 72.446400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2100-8100',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #100',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0101',
    facilityName: 'Gujarat Blood Center #101 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0101',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 22.982500,
    longitude: 72.561400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2101-8101',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #101',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0102',
    facilityName: 'Gujarat Blood Center #102 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0102',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 23.067500,
    longitude: 72.676400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2102-8102',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #102',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0103',
    facilityName: 'Gujarat Blood Center #103 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0103',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 22.902500,
    longitude: 72.541400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2103-8103',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #103',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0104',
    facilityName: 'Gujarat Blood Center #104 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0104',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 22.987500,
    longitude: 72.656400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2104-8104',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #104',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0105',
    facilityName: 'Gujarat Blood Center #105 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0105',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 23.072500,
    longitude: 72.521400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2105-8105',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #105',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0106',
    facilityName: 'Gujarat Blood Center #106 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0106',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 22.907500,
    longitude: 72.636400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2106-8106',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #106',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0107',
    facilityName: 'Gujarat Blood Center #107 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0107',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 22.992500,
    longitude: 72.501400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2107-8107',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #107',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0108',
    facilityName: 'Gujarat Blood Center #108 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2020/0108',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 23.077500,
    longitude: 72.616400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2108-8108',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #108',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-GUJA-0109',
    facilityName: 'Gujarat Blood Center #109 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2021/0109',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 22.912500,
    longitude: 72.481400,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2109-8109',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #109',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-GUJA-0110',
    facilityName: 'Gujarat Blood Center #110 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2022/0110',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 22.997500,
    longitude: 72.596400,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2110-8110',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #110',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-GUJA-0111',
    facilityName: 'Gujarat Blood Center #111 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2023/0111',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 23.082500,
    longitude: 72.461400,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2111-8111',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #111',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-GUJA-0112',
    facilityName: 'Gujarat Blood Center #112 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2024/0112',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 22.917500,
    longitude: 72.576400,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2112-8112',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #112',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-GUJA-0113',
    facilityName: 'Gujarat Blood Center #113 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-GUJ-2025/0113',
    stateRegion: 'Gujarat — Ahmedabad & Gandhinagar Belt',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 23.002500,
    longitude: 72.691400,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2113-8113',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Guja #113',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
];

export function getGujaratAhmedabadFacilityById(id: string): BloodBankFacilityRecord | undefined {
  return GUJARATAHMEDABAD_FACILITIES.find(f => f.id === id);
}

export function calculateHaversineDistanceKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371;
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a = Math.sin(dLat/2) * Math.sin(dLat/2) + Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLon/2) * Math.sin(dLon/2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
  return R * c;
}
