/**
 * BloodBridge Geo Registry — Karnataka — Bengaluru Urban & Rural
 * Licensed blood banks, trauma centers, and cold chain distribution hubs.
 */

export interface BloodBankFacilityRecord {
  id: string;
  facilityName: string;
  licenseNumber: string;
  stateRegion: string;
  districtCity: string;
  latitude: number;
  longitude: number;
  category: 'GOVERNMENT_MEDICAL_COLLEGE' | 'RED_CROSS_REGIONAL' | 'PRIVATE_TERTIARY' | 'DEFENCE_MILITARY' | 'CHARITABLE_TRUST';
  componentSeparationLicensed: boolean;
  apheresisAvailable: boolean;
  natTestingAvailable: boolean;
  refrigeratedCentrifugeUnits: number;
  deepFreezersMinus80Count: number;
  plateletAgitatorsCount: number;
  averageMonthlyCollectionUnits: number;
  emergencyContactPhone: string;
  nodalTransfusionOfficer: string;
  operatingHours: string;
  greenCorridorDispatchEnabled: boolean;
  backupGeneratorCapacityKva: number;
}

export const KARNATAKABENGALURU_FACILITIES: BloodBankFacilityRecord[] = [
  {
    id: 'FAC-KARN-0001',
    facilityName: 'Karnataka Blood Center #1 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0001',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 12.931600,
    longitude: 77.584600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2001-8001',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #1',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0002',
    facilityName: 'Karnataka Blood Center #2 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0002',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.016600,
    longitude: 77.699600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2002-8002',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #2',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0003',
    facilityName: 'Karnataka Blood Center #3 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0003',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.851600,
    longitude: 77.564600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2003-8003',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #3',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0004',
    facilityName: 'Karnataka Blood Center #4 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0004',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 12.936600,
    longitude: 77.679600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2004-8004',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #4',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0005',
    facilityName: 'Karnataka Blood Center #5 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0005',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.021600,
    longitude: 77.544600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2005-8005',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #5',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0006',
    facilityName: 'Karnataka Blood Center #6 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0006',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.856600,
    longitude: 77.659600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2006-8006',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #6',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0007',
    facilityName: 'Karnataka Blood Center #7 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0007',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 12.941600,
    longitude: 77.524600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2007-8007',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #7',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0008',
    facilityName: 'Karnataka Blood Center #8 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0008',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.026600,
    longitude: 77.639600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2008-8008',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #8',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0009',
    facilityName: 'Karnataka Blood Center #9 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0009',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.861600,
    longitude: 77.504600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2009-8009',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #9',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0010',
    facilityName: 'Karnataka Blood Center #10 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0010',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 12.946600,
    longitude: 77.619600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2010-8010',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #10',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0011',
    facilityName: 'Karnataka Blood Center #11 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0011',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.031600,
    longitude: 77.484600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2011-8011',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #11',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0012',
    facilityName: 'Karnataka Blood Center #12 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0012',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.866600,
    longitude: 77.599600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2012-8012',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #12',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0013',
    facilityName: 'Karnataka Blood Center #13 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0013',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 12.951600,
    longitude: 77.714600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2013-8013',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #13',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0014',
    facilityName: 'Karnataka Blood Center #14 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0014',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.036600,
    longitude: 77.579600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2014-8014',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #14',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0015',
    facilityName: 'Karnataka Blood Center #15 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0015',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.871600,
    longitude: 77.694600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2015-8015',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #15',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0016',
    facilityName: 'Karnataka Blood Center #16 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0016',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 12.956600,
    longitude: 77.559600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2016-8016',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #16',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0017',
    facilityName: 'Karnataka Blood Center #17 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0017',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.041600,
    longitude: 77.674600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2017-8017',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #17',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0018',
    facilityName: 'Karnataka Blood Center #18 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0018',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.876600,
    longitude: 77.539600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2018-8018',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #18',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0019',
    facilityName: 'Karnataka Blood Center #19 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0019',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 12.961600,
    longitude: 77.654600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2019-8019',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #19',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0020',
    facilityName: 'Karnataka Blood Center #20 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0020',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.046600,
    longitude: 77.519600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2020-8020',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #20',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0021',
    facilityName: 'Karnataka Blood Center #21 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0021',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.881600,
    longitude: 77.634600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2021-8021',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #21',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0022',
    facilityName: 'Karnataka Blood Center #22 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0022',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 12.966600,
    longitude: 77.499600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2022-8022',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #22',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0023',
    facilityName: 'Karnataka Blood Center #23 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0023',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.051600,
    longitude: 77.614600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2023-8023',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #23',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0024',
    facilityName: 'Karnataka Blood Center #24 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0024',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.886600,
    longitude: 77.479600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2024-8024',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #24',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0025',
    facilityName: 'Karnataka Blood Center #25 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0025',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 12.971600,
    longitude: 77.594600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2025-8025',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #25',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0026',
    facilityName: 'Karnataka Blood Center #26 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0026',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.056600,
    longitude: 77.709600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2026-8026',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #26',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0027',
    facilityName: 'Karnataka Blood Center #27 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0027',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.891600,
    longitude: 77.574600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2027-8027',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #27',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0028',
    facilityName: 'Karnataka Blood Center #28 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0028',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 12.976600,
    longitude: 77.689600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2028-8028',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #28',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0029',
    facilityName: 'Karnataka Blood Center #29 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0029',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.061600,
    longitude: 77.554600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2029-8029',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #29',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0030',
    facilityName: 'Karnataka Blood Center #30 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0030',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.896600,
    longitude: 77.669600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2030-8030',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #30',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0031',
    facilityName: 'Karnataka Blood Center #31 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0031',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 12.981600,
    longitude: 77.534600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2031-8031',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #31',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0032',
    facilityName: 'Karnataka Blood Center #32 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0032',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.066600,
    longitude: 77.649600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2032-8032',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #32',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0033',
    facilityName: 'Karnataka Blood Center #33 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0033',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.901600,
    longitude: 77.514600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2033-8033',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #33',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0034',
    facilityName: 'Karnataka Blood Center #34 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0034',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 12.986600,
    longitude: 77.629600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2034-8034',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #34',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0035',
    facilityName: 'Karnataka Blood Center #35 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0035',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.071600,
    longitude: 77.494600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2035-8035',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #35',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0036',
    facilityName: 'Karnataka Blood Center #36 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0036',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.906600,
    longitude: 77.609600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2036-8036',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #36',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0037',
    facilityName: 'Karnataka Blood Center #37 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0037',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 12.991600,
    longitude: 77.474600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2037-8037',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #37',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0038',
    facilityName: 'Karnataka Blood Center #38 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0038',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.076600,
    longitude: 77.589600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2038-8038',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #38',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0039',
    facilityName: 'Karnataka Blood Center #39 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0039',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.911600,
    longitude: 77.704600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2039-8039',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #39',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0040',
    facilityName: 'Karnataka Blood Center #40 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0040',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 12.996600,
    longitude: 77.569600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2040-8040',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #40',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0041',
    facilityName: 'Karnataka Blood Center #41 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0041',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.081600,
    longitude: 77.684600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2041-8041',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #41',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0042',
    facilityName: 'Karnataka Blood Center #42 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0042',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.916600,
    longitude: 77.549600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2042-8042',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #42',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0043',
    facilityName: 'Karnataka Blood Center #43 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0043',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.001600,
    longitude: 77.664600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2043-8043',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #43',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0044',
    facilityName: 'Karnataka Blood Center #44 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0044',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.086600,
    longitude: 77.529600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2044-8044',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #44',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0045',
    facilityName: 'Karnataka Blood Center #45 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0045',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.921600,
    longitude: 77.644600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2045-8045',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #45',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0046',
    facilityName: 'Karnataka Blood Center #46 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0046',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.006600,
    longitude: 77.509600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2046-8046',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #46',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0047',
    facilityName: 'Karnataka Blood Center #47 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0047',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.091600,
    longitude: 77.624600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2047-8047',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #47',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0048',
    facilityName: 'Karnataka Blood Center #48 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0048',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.926600,
    longitude: 77.489600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2048-8048',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #48',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0049',
    facilityName: 'Karnataka Blood Center #49 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0049',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.011600,
    longitude: 77.604600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2049-8049',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #49',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0050',
    facilityName: 'Karnataka Blood Center #50 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0050',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.846600,
    longitude: 77.469600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2050-8050',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #50',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0051',
    facilityName: 'Karnataka Blood Center #51 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0051',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.931600,
    longitude: 77.584600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2051-8051',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #51',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0052',
    facilityName: 'Karnataka Blood Center #52 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0052',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.016600,
    longitude: 77.699600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2052-8052',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #52',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0053',
    facilityName: 'Karnataka Blood Center #53 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0053',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 12.851600,
    longitude: 77.564600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2053-8053',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #53',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0054',
    facilityName: 'Karnataka Blood Center #54 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0054',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.936600,
    longitude: 77.679600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2054-8054',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #54',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0055',
    facilityName: 'Karnataka Blood Center #55 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0055',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.021600,
    longitude: 77.544600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2055-8055',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #55',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0056',
    facilityName: 'Karnataka Blood Center #56 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0056',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.856600,
    longitude: 77.659600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2056-8056',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #56',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0057',
    facilityName: 'Karnataka Blood Center #57 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0057',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.941600,
    longitude: 77.524600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2057-8057',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #57',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0058',
    facilityName: 'Karnataka Blood Center #58 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0058',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.026600,
    longitude: 77.639600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2058-8058',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #58',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0059',
    facilityName: 'Karnataka Blood Center #59 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0059',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 12.861600,
    longitude: 77.504600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2059-8059',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #59',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0060',
    facilityName: 'Karnataka Blood Center #60 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0060',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.946600,
    longitude: 77.619600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2060-8060',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #60',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0061',
    facilityName: 'Karnataka Blood Center #61 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0061',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.031600,
    longitude: 77.484600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2061-8061',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #61',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0062',
    facilityName: 'Karnataka Blood Center #62 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0062',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.866600,
    longitude: 77.599600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2062-8062',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #62',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0063',
    facilityName: 'Karnataka Blood Center #63 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0063',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.951600,
    longitude: 77.714600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2063-8063',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #63',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0064',
    facilityName: 'Karnataka Blood Center #64 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0064',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.036600,
    longitude: 77.579600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2064-8064',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #64',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0065',
    facilityName: 'Karnataka Blood Center #65 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0065',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 12.871600,
    longitude: 77.694600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2065-8065',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #65',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0066',
    facilityName: 'Karnataka Blood Center #66 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0066',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.956600,
    longitude: 77.559600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2066-8066',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #66',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0067',
    facilityName: 'Karnataka Blood Center #67 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0067',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.041600,
    longitude: 77.674600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2067-8067',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #67',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0068',
    facilityName: 'Karnataka Blood Center #68 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0068',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.876600,
    longitude: 77.539600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2068-8068',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #68',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0069',
    facilityName: 'Karnataka Blood Center #69 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0069',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.961600,
    longitude: 77.654600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2069-8069',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #69',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0070',
    facilityName: 'Karnataka Blood Center #70 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0070',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.046600,
    longitude: 77.519600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2070-8070',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #70',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0071',
    facilityName: 'Karnataka Blood Center #71 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0071',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 12.881600,
    longitude: 77.634600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2071-8071',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #71',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0072',
    facilityName: 'Karnataka Blood Center #72 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0072',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.966600,
    longitude: 77.499600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2072-8072',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #72',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0073',
    facilityName: 'Karnataka Blood Center #73 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0073',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.051600,
    longitude: 77.614600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2073-8073',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #73',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0074',
    facilityName: 'Karnataka Blood Center #74 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0074',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.886600,
    longitude: 77.479600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2074-8074',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #74',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0075',
    facilityName: 'Karnataka Blood Center #75 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0075',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.971600,
    longitude: 77.594600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2075-8075',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #75',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0076',
    facilityName: 'Karnataka Blood Center #76 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0076',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.056600,
    longitude: 77.709600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2076-8076',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #76',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0077',
    facilityName: 'Karnataka Blood Center #77 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0077',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 12.891600,
    longitude: 77.574600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2077-8077',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #77',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0078',
    facilityName: 'Karnataka Blood Center #78 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0078',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.976600,
    longitude: 77.689600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2078-8078',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #78',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0079',
    facilityName: 'Karnataka Blood Center #79 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0079',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.061600,
    longitude: 77.554600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2079-8079',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #79',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0080',
    facilityName: 'Karnataka Blood Center #80 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0080',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.896600,
    longitude: 77.669600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2080-8080',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #80',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0081',
    facilityName: 'Karnataka Blood Center #81 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0081',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.981600,
    longitude: 77.534600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2081-8081',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #81',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0082',
    facilityName: 'Karnataka Blood Center #82 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0082',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.066600,
    longitude: 77.649600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2082-8082',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #82',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0083',
    facilityName: 'Karnataka Blood Center #83 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0083',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 12.901600,
    longitude: 77.514600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2083-8083',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #83',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0084',
    facilityName: 'Karnataka Blood Center #84 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0084',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.986600,
    longitude: 77.629600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2084-8084',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #84',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0085',
    facilityName: 'Karnataka Blood Center #85 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0085',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.071600,
    longitude: 77.494600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2085-8085',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #85',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0086',
    facilityName: 'Karnataka Blood Center #86 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0086',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.906600,
    longitude: 77.609600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2086-8086',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #86',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0087',
    facilityName: 'Karnataka Blood Center #87 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0087',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.991600,
    longitude: 77.474600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2087-8087',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #87',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0088',
    facilityName: 'Karnataka Blood Center #88 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0088',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.076600,
    longitude: 77.589600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2088-8088',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #88',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0089',
    facilityName: 'Karnataka Blood Center #89 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0089',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 12.911600,
    longitude: 77.704600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2089-8089',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #89',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0090',
    facilityName: 'Karnataka Blood Center #90 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0090',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.996600,
    longitude: 77.569600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2090-8090',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #90',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0091',
    facilityName: 'Karnataka Blood Center #91 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0091',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.081600,
    longitude: 77.684600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2091-8091',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #91',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0092',
    facilityName: 'Karnataka Blood Center #92 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0092',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.916600,
    longitude: 77.549600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2092-8092',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #92',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0093',
    facilityName: 'Karnataka Blood Center #93 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0093',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.001600,
    longitude: 77.664600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2093-8093',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #93',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0094',
    facilityName: 'Karnataka Blood Center #94 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0094',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.086600,
    longitude: 77.529600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2094-8094',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #94',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0095',
    facilityName: 'Karnataka Blood Center #95 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0095',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 12.921600,
    longitude: 77.644600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2095-8095',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #95',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0096',
    facilityName: 'Karnataka Blood Center #96 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0096',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.006600,
    longitude: 77.509600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2096-8096',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #96',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0097',
    facilityName: 'Karnataka Blood Center #97 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0097',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.091600,
    longitude: 77.624600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2097-8097',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #97',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0098',
    facilityName: 'Karnataka Blood Center #98 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0098',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.926600,
    longitude: 77.489600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2098-8098',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #98',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0099',
    facilityName: 'Karnataka Blood Center #99 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0099',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.011600,
    longitude: 77.604600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2099-8099',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #99',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0100',
    facilityName: 'Karnataka Blood Center #100 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0100',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 12.846600,
    longitude: 77.469600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2100-8100',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #100',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0101',
    facilityName: 'Karnataka Blood Center #101 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0101',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 12.931600,
    longitude: 77.584600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2101-8101',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #101',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0102',
    facilityName: 'Karnataka Blood Center #102 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0102',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.016600,
    longitude: 77.699600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2102-8102',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #102',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0103',
    facilityName: 'Karnataka Blood Center #103 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0103',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 12.851600,
    longitude: 77.564600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2103-8103',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #103',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0104',
    facilityName: 'Karnataka Blood Center #104 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0104',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.936600,
    longitude: 77.679600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2104-8104',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #104',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0105',
    facilityName: 'Karnataka Blood Center #105 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0105',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.021600,
    longitude: 77.544600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2105-8105',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #105',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0106',
    facilityName: 'Karnataka Blood Center #106 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0106',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 12.856600,
    longitude: 77.659600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2106-8106',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #106',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0107',
    facilityName: 'Karnataka Blood Center #107 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0107',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 12.941600,
    longitude: 77.524600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2107-8107',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #107',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0108',
    facilityName: 'Karnataka Blood Center #108 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2020/0108',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.026600,
    longitude: 77.639600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2108-8108',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #108',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KARN-0109',
    facilityName: 'Karnataka Blood Center #109 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2021/0109',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 12.861600,
    longitude: 77.504600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2109-8109',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #109',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KARN-0110',
    facilityName: 'Karnataka Blood Center #110 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2022/0110',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.946600,
    longitude: 77.619600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2110-8110',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #110',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KARN-0111',
    facilityName: 'Karnataka Blood Center #111 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2023/0111',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.031600,
    longitude: 77.484600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2111-8111',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #111',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KARN-0112',
    facilityName: 'Karnataka Blood Center #112 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2024/0112',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 12.866600,
    longitude: 77.599600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2112-8112',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #112',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KARN-0113',
    facilityName: 'Karnataka Blood Center #113 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KAR-2025/0113',
    stateRegion: 'Karnataka — Bengaluru Urban & Rural',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 12.951600,
    longitude: 77.714600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2113-8113',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Karn #113',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
];

export function getKarnatakaBengaluruFacilityById(id: string): BloodBankFacilityRecord | undefined {
  return KARNATAKABENGALURU_FACILITIES.find(f => f.id === id);
}

export function calculateHaversineDistanceKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371;
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a = Math.sin(dLat/2) * Math.sin(dLat/2) + Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLon/2) * Math.sin(dLon/2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
  return R * c;
}
