/**
 * BloodBridge Geo Registry — Kerala — Thiruvananthapuram & South Zone
 * Licensed blood banks, trauma centers, and cold chain distribution hubs.
 */

export interface BloodBankFacilityRecord {
  id: string;
  facilityName: string;
  licenseNumber: string;
  stateRegion: string;
  districtCity: string;
  latitude: number;
  longitude: number;
  category: 'GOVERNMENT_MEDICAL_COLLEGE' | 'RED_CROSS_REGIONAL' | 'PRIVATE_TERTIARY' | 'DEFENCE_MILITARY' | 'CHARITABLE_TRUST';
  componentSeparationLicensed: boolean;
  apheresisAvailable: boolean;
  natTestingAvailable: boolean;
  refrigeratedCentrifugeUnits: number;
  deepFreezersMinus80Count: number;
  plateletAgitatorsCount: number;
  averageMonthlyCollectionUnits: number;
  emergencyContactPhone: string;
  nodalTransfusionOfficer: string;
  operatingHours: string;
  greenCorridorDispatchEnabled: boolean;
  backupGeneratorCapacityKva: number;
}

export const KERALATHIRUVANANTHAPURAM_FACILITIES: BloodBankFacilityRecord[] = [
  {
    id: 'FAC-KERA-0001',
    facilityName: 'Kerala Blood Center #1 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0001',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.484100,
    longitude: 76.926600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2001-8001',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #1',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0002',
    facilityName: 'Kerala Blood Center #2 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0002',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.569100,
    longitude: 77.041600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2002-8002',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #2',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0003',
    facilityName: 'Kerala Blood Center #3 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0003',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.404100,
    longitude: 76.906600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2003-8003',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #3',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0004',
    facilityName: 'Kerala Blood Center #4 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0004',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.489100,
    longitude: 77.021600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2004-8004',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #4',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0005',
    facilityName: 'Kerala Blood Center #5 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0005',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.574100,
    longitude: 76.886600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2005-8005',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #5',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0006',
    facilityName: 'Kerala Blood Center #6 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0006',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.409100,
    longitude: 77.001600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2006-8006',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #6',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0007',
    facilityName: 'Kerala Blood Center #7 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0007',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.494100,
    longitude: 76.866600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2007-8007',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #7',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0008',
    facilityName: 'Kerala Blood Center #8 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0008',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.579100,
    longitude: 76.981600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2008-8008',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #8',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0009',
    facilityName: 'Kerala Blood Center #9 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0009',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.414100,
    longitude: 76.846600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2009-8009',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #9',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0010',
    facilityName: 'Kerala Blood Center #10 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0010',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.499100,
    longitude: 76.961600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2010-8010',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #10',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0011',
    facilityName: 'Kerala Blood Center #11 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0011',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.584100,
    longitude: 76.826600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2011-8011',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #11',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0012',
    facilityName: 'Kerala Blood Center #12 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0012',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.419100,
    longitude: 76.941600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2012-8012',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #12',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0013',
    facilityName: 'Kerala Blood Center #13 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0013',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.504100,
    longitude: 77.056600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2013-8013',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #13',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0014',
    facilityName: 'Kerala Blood Center #14 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0014',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.589100,
    longitude: 76.921600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2014-8014',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #14',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0015',
    facilityName: 'Kerala Blood Center #15 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0015',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.424100,
    longitude: 77.036600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2015-8015',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #15',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0016',
    facilityName: 'Kerala Blood Center #16 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0016',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.509100,
    longitude: 76.901600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2016-8016',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #16',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0017',
    facilityName: 'Kerala Blood Center #17 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0017',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.594100,
    longitude: 77.016600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2017-8017',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #17',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0018',
    facilityName: 'Kerala Blood Center #18 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0018',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.429100,
    longitude: 76.881600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2018-8018',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #18',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0019',
    facilityName: 'Kerala Blood Center #19 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0019',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.514100,
    longitude: 76.996600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2019-8019',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #19',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0020',
    facilityName: 'Kerala Blood Center #20 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0020',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.599100,
    longitude: 76.861600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2020-8020',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #20',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0021',
    facilityName: 'Kerala Blood Center #21 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0021',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.434100,
    longitude: 76.976600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2021-8021',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #21',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0022',
    facilityName: 'Kerala Blood Center #22 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0022',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.519100,
    longitude: 76.841600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2022-8022',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #22',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0023',
    facilityName: 'Kerala Blood Center #23 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0023',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.604100,
    longitude: 76.956600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2023-8023',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #23',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0024',
    facilityName: 'Kerala Blood Center #24 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0024',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.439100,
    longitude: 76.821600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2024-8024',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #24',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0025',
    facilityName: 'Kerala Blood Center #25 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0025',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.524100,
    longitude: 76.936600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2025-8025',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #25',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0026',
    facilityName: 'Kerala Blood Center #26 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0026',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.609100,
    longitude: 77.051600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2026-8026',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #26',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0027',
    facilityName: 'Kerala Blood Center #27 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0027',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.444100,
    longitude: 76.916600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2027-8027',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #27',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0028',
    facilityName: 'Kerala Blood Center #28 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0028',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.529100,
    longitude: 77.031600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2028-8028',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #28',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0029',
    facilityName: 'Kerala Blood Center #29 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0029',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.614100,
    longitude: 76.896600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2029-8029',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #29',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0030',
    facilityName: 'Kerala Blood Center #30 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0030',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.449100,
    longitude: 77.011600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2030-8030',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #30',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0031',
    facilityName: 'Kerala Blood Center #31 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0031',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.534100,
    longitude: 76.876600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2031-8031',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #31',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0032',
    facilityName: 'Kerala Blood Center #32 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0032',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.619100,
    longitude: 76.991600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2032-8032',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #32',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0033',
    facilityName: 'Kerala Blood Center #33 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0033',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.454100,
    longitude: 76.856600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2033-8033',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #33',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0034',
    facilityName: 'Kerala Blood Center #34 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0034',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.539100,
    longitude: 76.971600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2034-8034',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #34',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0035',
    facilityName: 'Kerala Blood Center #35 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0035',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.624100,
    longitude: 76.836600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2035-8035',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #35',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0036',
    facilityName: 'Kerala Blood Center #36 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0036',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.459100,
    longitude: 76.951600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2036-8036',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #36',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0037',
    facilityName: 'Kerala Blood Center #37 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0037',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.544100,
    longitude: 76.816600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2037-8037',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #37',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0038',
    facilityName: 'Kerala Blood Center #38 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0038',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.629100,
    longitude: 76.931600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2038-8038',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #38',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0039',
    facilityName: 'Kerala Blood Center #39 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0039',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.464100,
    longitude: 77.046600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2039-8039',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #39',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0040',
    facilityName: 'Kerala Blood Center #40 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0040',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.549100,
    longitude: 76.911600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2040-8040',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #40',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0041',
    facilityName: 'Kerala Blood Center #41 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0041',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.634100,
    longitude: 77.026600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2041-8041',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #41',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0042',
    facilityName: 'Kerala Blood Center #42 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0042',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.469100,
    longitude: 76.891600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2042-8042',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #42',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0043',
    facilityName: 'Kerala Blood Center #43 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0043',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.554100,
    longitude: 77.006600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2043-8043',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #43',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0044',
    facilityName: 'Kerala Blood Center #44 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0044',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.639100,
    longitude: 76.871600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2044-8044',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #44',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0045',
    facilityName: 'Kerala Blood Center #45 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0045',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.474100,
    longitude: 76.986600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2045-8045',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #45',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0046',
    facilityName: 'Kerala Blood Center #46 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0046',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.559100,
    longitude: 76.851600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2046-8046',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #46',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0047',
    facilityName: 'Kerala Blood Center #47 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0047',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.644100,
    longitude: 76.966600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2047-8047',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #47',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0048',
    facilityName: 'Kerala Blood Center #48 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0048',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.479100,
    longitude: 76.831600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2048-8048',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #48',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0049',
    facilityName: 'Kerala Blood Center #49 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0049',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.564100,
    longitude: 76.946600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2049-8049',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #49',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0050',
    facilityName: 'Kerala Blood Center #50 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0050',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.399100,
    longitude: 76.811600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2050-8050',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #50',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0051',
    facilityName: 'Kerala Blood Center #51 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0051',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.484100,
    longitude: 76.926600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2051-8051',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #51',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0052',
    facilityName: 'Kerala Blood Center #52 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0052',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.569100,
    longitude: 77.041600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2052-8052',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #52',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0053',
    facilityName: 'Kerala Blood Center #53 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0053',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.404100,
    longitude: 76.906600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2053-8053',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #53',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0054',
    facilityName: 'Kerala Blood Center #54 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0054',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.489100,
    longitude: 77.021600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2054-8054',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #54',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0055',
    facilityName: 'Kerala Blood Center #55 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0055',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.574100,
    longitude: 76.886600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2055-8055',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #55',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0056',
    facilityName: 'Kerala Blood Center #56 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0056',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.409100,
    longitude: 77.001600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2056-8056',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #56',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0057',
    facilityName: 'Kerala Blood Center #57 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0057',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.494100,
    longitude: 76.866600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2057-8057',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #57',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0058',
    facilityName: 'Kerala Blood Center #58 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0058',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.579100,
    longitude: 76.981600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2058-8058',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #58',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0059',
    facilityName: 'Kerala Blood Center #59 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0059',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.414100,
    longitude: 76.846600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2059-8059',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #59',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0060',
    facilityName: 'Kerala Blood Center #60 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0060',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.499100,
    longitude: 76.961600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2060-8060',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #60',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0061',
    facilityName: 'Kerala Blood Center #61 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0061',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.584100,
    longitude: 76.826600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2061-8061',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #61',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0062',
    facilityName: 'Kerala Blood Center #62 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0062',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.419100,
    longitude: 76.941600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2062-8062',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #62',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0063',
    facilityName: 'Kerala Blood Center #63 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0063',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.504100,
    longitude: 77.056600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2063-8063',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #63',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0064',
    facilityName: 'Kerala Blood Center #64 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0064',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.589100,
    longitude: 76.921600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2064-8064',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #64',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0065',
    facilityName: 'Kerala Blood Center #65 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0065',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.424100,
    longitude: 77.036600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2065-8065',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #65',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0066',
    facilityName: 'Kerala Blood Center #66 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0066',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.509100,
    longitude: 76.901600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2066-8066',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #66',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0067',
    facilityName: 'Kerala Blood Center #67 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0067',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.594100,
    longitude: 77.016600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2067-8067',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #67',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0068',
    facilityName: 'Kerala Blood Center #68 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0068',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.429100,
    longitude: 76.881600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2068-8068',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #68',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0069',
    facilityName: 'Kerala Blood Center #69 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0069',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.514100,
    longitude: 76.996600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2069-8069',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #69',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0070',
    facilityName: 'Kerala Blood Center #70 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0070',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.599100,
    longitude: 76.861600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2070-8070',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #70',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0071',
    facilityName: 'Kerala Blood Center #71 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0071',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.434100,
    longitude: 76.976600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2071-8071',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #71',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0072',
    facilityName: 'Kerala Blood Center #72 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0072',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.519100,
    longitude: 76.841600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2072-8072',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #72',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0073',
    facilityName: 'Kerala Blood Center #73 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0073',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.604100,
    longitude: 76.956600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2073-8073',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #73',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0074',
    facilityName: 'Kerala Blood Center #74 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0074',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.439100,
    longitude: 76.821600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2074-8074',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #74',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0075',
    facilityName: 'Kerala Blood Center #75 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0075',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.524100,
    longitude: 76.936600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2075-8075',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #75',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0076',
    facilityName: 'Kerala Blood Center #76 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0076',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.609100,
    longitude: 77.051600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2076-8076',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #76',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0077',
    facilityName: 'Kerala Blood Center #77 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0077',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.444100,
    longitude: 76.916600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2077-8077',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #77',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0078',
    facilityName: 'Kerala Blood Center #78 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0078',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.529100,
    longitude: 77.031600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2078-8078',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #78',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0079',
    facilityName: 'Kerala Blood Center #79 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0079',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.614100,
    longitude: 76.896600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2079-8079',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #79',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0080',
    facilityName: 'Kerala Blood Center #80 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0080',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.449100,
    longitude: 77.011600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2080-8080',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #80',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0081',
    facilityName: 'Kerala Blood Center #81 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0081',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.534100,
    longitude: 76.876600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2081-8081',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #81',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0082',
    facilityName: 'Kerala Blood Center #82 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0082',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.619100,
    longitude: 76.991600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2082-8082',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #82',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0083',
    facilityName: 'Kerala Blood Center #83 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0083',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.454100,
    longitude: 76.856600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2083-8083',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #83',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0084',
    facilityName: 'Kerala Blood Center #84 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0084',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.539100,
    longitude: 76.971600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2084-8084',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #84',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0085',
    facilityName: 'Kerala Blood Center #85 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0085',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.624100,
    longitude: 76.836600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2085-8085',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #85',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0086',
    facilityName: 'Kerala Blood Center #86 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0086',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.459100,
    longitude: 76.951600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2086-8086',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #86',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0087',
    facilityName: 'Kerala Blood Center #87 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0087',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.544100,
    longitude: 76.816600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2087-8087',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #87',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0088',
    facilityName: 'Kerala Blood Center #88 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0088',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.629100,
    longitude: 76.931600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2088-8088',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #88',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0089',
    facilityName: 'Kerala Blood Center #89 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0089',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.464100,
    longitude: 77.046600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2089-8089',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #89',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0090',
    facilityName: 'Kerala Blood Center #90 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0090',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.549100,
    longitude: 76.911600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2090-8090',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #90',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0091',
    facilityName: 'Kerala Blood Center #91 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0091',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.634100,
    longitude: 77.026600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2091-8091',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #91',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0092',
    facilityName: 'Kerala Blood Center #92 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0092',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.469100,
    longitude: 76.891600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2092-8092',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #92',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0093',
    facilityName: 'Kerala Blood Center #93 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0093',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.554100,
    longitude: 77.006600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2093-8093',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #93',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0094',
    facilityName: 'Kerala Blood Center #94 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0094',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.639100,
    longitude: 76.871600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2094-8094',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #94',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0095',
    facilityName: 'Kerala Blood Center #95 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0095',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.474100,
    longitude: 76.986600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2095-8095',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #95',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0096',
    facilityName: 'Kerala Blood Center #96 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0096',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.559100,
    longitude: 76.851600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2096-8096',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #96',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0097',
    facilityName: 'Kerala Blood Center #97 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0097',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.644100,
    longitude: 76.966600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2097-8097',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #97',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0098',
    facilityName: 'Kerala Blood Center #98 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0098',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.479100,
    longitude: 76.831600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2098-8098',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #98',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0099',
    facilityName: 'Kerala Blood Center #99 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0099',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.564100,
    longitude: 76.946600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2099-8099',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #99',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0100',
    facilityName: 'Kerala Blood Center #100 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0100',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.399100,
    longitude: 76.811600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2100-8100',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #100',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0101',
    facilityName: 'Kerala Blood Center #101 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0101',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.484100,
    longitude: 76.926600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2101-8101',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #101',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0102',
    facilityName: 'Kerala Blood Center #102 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0102',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.569100,
    longitude: 77.041600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2102-8102',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #102',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0103',
    facilityName: 'Kerala Blood Center #103 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0103',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.404100,
    longitude: 76.906600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2103-8103',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #103',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0104',
    facilityName: 'Kerala Blood Center #104 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0104',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.489100,
    longitude: 77.021600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2104-8104',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #104',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0105',
    facilityName: 'Kerala Blood Center #105 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0105',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.574100,
    longitude: 76.886600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2105-8105',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #105',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0106',
    facilityName: 'Kerala Blood Center #106 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0106',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.409100,
    longitude: 77.001600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2106-8106',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #106',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0107',
    facilityName: 'Kerala Blood Center #107 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0107',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.494100,
    longitude: 76.866600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2107-8107',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #107',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0108',
    facilityName: 'Kerala Blood Center #108 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2020/0108',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 8.579100,
    longitude: 76.981600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2108-8108',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #108',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-KERA-0109',
    facilityName: 'Kerala Blood Center #109 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2021/0109',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 8.414100,
    longitude: 76.846600,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2109-8109',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #109',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-KERA-0110',
    facilityName: 'Kerala Blood Center #110 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2022/0110',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 8.499100,
    longitude: 76.961600,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2110-8110',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #110',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-KERA-0111',
    facilityName: 'Kerala Blood Center #111 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2023/0111',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 8.584100,
    longitude: 76.826600,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2111-8111',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #111',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-KERA-0112',
    facilityName: 'Kerala Blood Center #112 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2024/0112',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 8.419100,
    longitude: 76.941600,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2112-8112',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #112',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-KERA-0113',
    facilityName: 'Kerala Blood Center #113 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-KER-2025/0113',
    stateRegion: 'Kerala — Thiruvananthapuram & South Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 8.504100,
    longitude: 77.056600,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2113-8113',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Kera #113',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
];

export function getKeralaThiruvananthapuramFacilityById(id: string): BloodBankFacilityRecord | undefined {
  return KERALATHIRUVANANTHAPURAM_FACILITIES.find(f => f.id === id);
}

export function calculateHaversineDistanceKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371;
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a = Math.sin(dLat/2) * Math.sin(dLat/2) + Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLon/2) * Math.sin(dLon/2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
  return R * c;
}
