/**
 * BloodBridge Geo Registry — Odisha — Bhubaneswar & Cuttack Twin Cities
 * Licensed blood banks, trauma centers, and cold chain distribution hubs.
 */

export interface BloodBankFacilityRecord {
  id: string;
  facilityName: string;
  licenseNumber: string;
  stateRegion: string;
  districtCity: string;
  latitude: number;
  longitude: number;
  category: 'GOVERNMENT_MEDICAL_COLLEGE' | 'RED_CROSS_REGIONAL' | 'PRIVATE_TERTIARY' | 'DEFENCE_MILITARY' | 'CHARITABLE_TRUST';
  componentSeparationLicensed: boolean;
  apheresisAvailable: boolean;
  natTestingAvailable: boolean;
  refrigeratedCentrifugeUnits: number;
  deepFreezersMinus80Count: number;
  plateletAgitatorsCount: number;
  averageMonthlyCollectionUnits: number;
  emergencyContactPhone: string;
  nodalTransfusionOfficer: string;
  operatingHours: string;
  greenCorridorDispatchEnabled: boolean;
  backupGeneratorCapacityKva: number;
}

export const ODISHABHUBANESWAR_FACILITIES: BloodBankFacilityRecord[] = [
  {
    id: 'FAC-ODIS-0001',
    facilityName: 'Odisha Blood Center #1 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0001',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.256100,
    longitude: 85.814500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2001-8001',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #1',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0002',
    facilityName: 'Odisha Blood Center #2 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0002',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.341100,
    longitude: 85.929500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2002-8002',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #2',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0003',
    facilityName: 'Odisha Blood Center #3 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0003',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.176100,
    longitude: 85.794500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2003-8003',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #3',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0004',
    facilityName: 'Odisha Blood Center #4 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0004',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.261100,
    longitude: 85.909500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2004-8004',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #4',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0005',
    facilityName: 'Odisha Blood Center #5 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0005',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.346100,
    longitude: 85.774500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2005-8005',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #5',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0006',
    facilityName: 'Odisha Blood Center #6 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0006',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.181100,
    longitude: 85.889500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2006-8006',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #6',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0007',
    facilityName: 'Odisha Blood Center #7 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0007',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.266100,
    longitude: 85.754500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2007-8007',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #7',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0008',
    facilityName: 'Odisha Blood Center #8 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0008',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.351100,
    longitude: 85.869500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2008-8008',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #8',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0009',
    facilityName: 'Odisha Blood Center #9 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0009',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.186100,
    longitude: 85.734500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2009-8009',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #9',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0010',
    facilityName: 'Odisha Blood Center #10 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0010',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.271100,
    longitude: 85.849500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2010-8010',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #10',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0011',
    facilityName: 'Odisha Blood Center #11 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0011',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.356100,
    longitude: 85.714500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2011-8011',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #11',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0012',
    facilityName: 'Odisha Blood Center #12 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0012',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.191100,
    longitude: 85.829500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2012-8012',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #12',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0013',
    facilityName: 'Odisha Blood Center #13 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0013',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.276100,
    longitude: 85.944500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2013-8013',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #13',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0014',
    facilityName: 'Odisha Blood Center #14 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0014',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.361100,
    longitude: 85.809500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2014-8014',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #14',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0015',
    facilityName: 'Odisha Blood Center #15 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0015',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.196100,
    longitude: 85.924500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2015-8015',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #15',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0016',
    facilityName: 'Odisha Blood Center #16 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0016',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.281100,
    longitude: 85.789500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2016-8016',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #16',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0017',
    facilityName: 'Odisha Blood Center #17 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0017',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.366100,
    longitude: 85.904500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2017-8017',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #17',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0018',
    facilityName: 'Odisha Blood Center #18 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0018',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.201100,
    longitude: 85.769500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2018-8018',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #18',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0019',
    facilityName: 'Odisha Blood Center #19 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0019',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.286100,
    longitude: 85.884500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2019-8019',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #19',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0020',
    facilityName: 'Odisha Blood Center #20 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0020',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.371100,
    longitude: 85.749500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2020-8020',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #20',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0021',
    facilityName: 'Odisha Blood Center #21 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0021',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.206100,
    longitude: 85.864500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2021-8021',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #21',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0022',
    facilityName: 'Odisha Blood Center #22 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0022',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.291100,
    longitude: 85.729500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2022-8022',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #22',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0023',
    facilityName: 'Odisha Blood Center #23 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0023',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.376100,
    longitude: 85.844500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2023-8023',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #23',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0024',
    facilityName: 'Odisha Blood Center #24 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0024',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.211100,
    longitude: 85.709500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2024-8024',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #24',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0025',
    facilityName: 'Odisha Blood Center #25 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0025',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.296100,
    longitude: 85.824500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2025-8025',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #25',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0026',
    facilityName: 'Odisha Blood Center #26 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0026',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.381100,
    longitude: 85.939500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2026-8026',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #26',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0027',
    facilityName: 'Odisha Blood Center #27 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0027',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.216100,
    longitude: 85.804500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2027-8027',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #27',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0028',
    facilityName: 'Odisha Blood Center #28 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0028',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.301100,
    longitude: 85.919500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2028-8028',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #28',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0029',
    facilityName: 'Odisha Blood Center #29 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0029',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.386100,
    longitude: 85.784500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2029-8029',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #29',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0030',
    facilityName: 'Odisha Blood Center #30 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0030',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.221100,
    longitude: 85.899500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2030-8030',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #30',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0031',
    facilityName: 'Odisha Blood Center #31 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0031',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.306100,
    longitude: 85.764500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2031-8031',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #31',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0032',
    facilityName: 'Odisha Blood Center #32 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0032',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.391100,
    longitude: 85.879500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2032-8032',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #32',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0033',
    facilityName: 'Odisha Blood Center #33 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0033',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.226100,
    longitude: 85.744500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2033-8033',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #33',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0034',
    facilityName: 'Odisha Blood Center #34 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0034',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.311100,
    longitude: 85.859500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2034-8034',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #34',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0035',
    facilityName: 'Odisha Blood Center #35 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0035',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.396100,
    longitude: 85.724500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2035-8035',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #35',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0036',
    facilityName: 'Odisha Blood Center #36 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0036',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.231100,
    longitude: 85.839500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2036-8036',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #36',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0037',
    facilityName: 'Odisha Blood Center #37 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0037',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.316100,
    longitude: 85.704500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2037-8037',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #37',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0038',
    facilityName: 'Odisha Blood Center #38 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0038',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.401100,
    longitude: 85.819500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2038-8038',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #38',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0039',
    facilityName: 'Odisha Blood Center #39 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0039',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.236100,
    longitude: 85.934500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2039-8039',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #39',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0040',
    facilityName: 'Odisha Blood Center #40 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0040',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.321100,
    longitude: 85.799500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2040-8040',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #40',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0041',
    facilityName: 'Odisha Blood Center #41 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0041',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.406100,
    longitude: 85.914500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2041-8041',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #41',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0042',
    facilityName: 'Odisha Blood Center #42 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0042',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.241100,
    longitude: 85.779500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2042-8042',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #42',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0043',
    facilityName: 'Odisha Blood Center #43 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0043',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.326100,
    longitude: 85.894500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2043-8043',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #43',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0044',
    facilityName: 'Odisha Blood Center #44 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0044',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.411100,
    longitude: 85.759500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2044-8044',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #44',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0045',
    facilityName: 'Odisha Blood Center #45 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0045',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.246100,
    longitude: 85.874500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2045-8045',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #45',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0046',
    facilityName: 'Odisha Blood Center #46 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0046',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.331100,
    longitude: 85.739500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2046-8046',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #46',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0047',
    facilityName: 'Odisha Blood Center #47 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0047',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.416100,
    longitude: 85.854500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2047-8047',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #47',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0048',
    facilityName: 'Odisha Blood Center #48 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0048',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.251100,
    longitude: 85.719500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2048-8048',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #48',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0049',
    facilityName: 'Odisha Blood Center #49 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0049',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.336100,
    longitude: 85.834500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2049-8049',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #49',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0050',
    facilityName: 'Odisha Blood Center #50 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0050',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.171100,
    longitude: 85.699500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2050-8050',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #50',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0051',
    facilityName: 'Odisha Blood Center #51 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0051',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.256100,
    longitude: 85.814500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2051-8051',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #51',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0052',
    facilityName: 'Odisha Blood Center #52 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0052',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.341100,
    longitude: 85.929500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2052-8052',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #52',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0053',
    facilityName: 'Odisha Blood Center #53 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0053',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.176100,
    longitude: 85.794500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2053-8053',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #53',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0054',
    facilityName: 'Odisha Blood Center #54 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0054',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.261100,
    longitude: 85.909500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2054-8054',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #54',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0055',
    facilityName: 'Odisha Blood Center #55 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0055',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.346100,
    longitude: 85.774500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2055-8055',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #55',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0056',
    facilityName: 'Odisha Blood Center #56 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0056',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.181100,
    longitude: 85.889500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2056-8056',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #56',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0057',
    facilityName: 'Odisha Blood Center #57 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0057',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.266100,
    longitude: 85.754500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2057-8057',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #57',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0058',
    facilityName: 'Odisha Blood Center #58 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0058',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.351100,
    longitude: 85.869500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2058-8058',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #58',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0059',
    facilityName: 'Odisha Blood Center #59 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0059',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.186100,
    longitude: 85.734500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2059-8059',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #59',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0060',
    facilityName: 'Odisha Blood Center #60 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0060',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.271100,
    longitude: 85.849500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2060-8060',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #60',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0061',
    facilityName: 'Odisha Blood Center #61 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0061',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.356100,
    longitude: 85.714500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2061-8061',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #61',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0062',
    facilityName: 'Odisha Blood Center #62 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0062',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.191100,
    longitude: 85.829500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2062-8062',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #62',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0063',
    facilityName: 'Odisha Blood Center #63 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0063',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.276100,
    longitude: 85.944500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2063-8063',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #63',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0064',
    facilityName: 'Odisha Blood Center #64 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0064',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.361100,
    longitude: 85.809500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2064-8064',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #64',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0065',
    facilityName: 'Odisha Blood Center #65 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0065',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.196100,
    longitude: 85.924500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2065-8065',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #65',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0066',
    facilityName: 'Odisha Blood Center #66 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0066',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.281100,
    longitude: 85.789500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2066-8066',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #66',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0067',
    facilityName: 'Odisha Blood Center #67 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0067',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.366100,
    longitude: 85.904500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2067-8067',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #67',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0068',
    facilityName: 'Odisha Blood Center #68 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0068',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.201100,
    longitude: 85.769500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2068-8068',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #68',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0069',
    facilityName: 'Odisha Blood Center #69 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0069',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.286100,
    longitude: 85.884500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2069-8069',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #69',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0070',
    facilityName: 'Odisha Blood Center #70 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0070',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.371100,
    longitude: 85.749500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2070-8070',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #70',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0071',
    facilityName: 'Odisha Blood Center #71 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0071',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.206100,
    longitude: 85.864500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2071-8071',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #71',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0072',
    facilityName: 'Odisha Blood Center #72 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0072',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.291100,
    longitude: 85.729500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2072-8072',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #72',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0073',
    facilityName: 'Odisha Blood Center #73 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0073',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.376100,
    longitude: 85.844500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2073-8073',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #73',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0074',
    facilityName: 'Odisha Blood Center #74 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0074',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.211100,
    longitude: 85.709500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2074-8074',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #74',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0075',
    facilityName: 'Odisha Blood Center #75 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0075',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.296100,
    longitude: 85.824500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2075-8075',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #75',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0076',
    facilityName: 'Odisha Blood Center #76 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0076',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.381100,
    longitude: 85.939500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2076-8076',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #76',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0077',
    facilityName: 'Odisha Blood Center #77 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0077',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.216100,
    longitude: 85.804500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2077-8077',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #77',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0078',
    facilityName: 'Odisha Blood Center #78 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0078',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.301100,
    longitude: 85.919500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2078-8078',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #78',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0079',
    facilityName: 'Odisha Blood Center #79 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0079',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.386100,
    longitude: 85.784500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2079-8079',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #79',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0080',
    facilityName: 'Odisha Blood Center #80 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0080',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.221100,
    longitude: 85.899500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2080-8080',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #80',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0081',
    facilityName: 'Odisha Blood Center #81 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0081',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.306100,
    longitude: 85.764500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2081-8081',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #81',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0082',
    facilityName: 'Odisha Blood Center #82 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0082',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.391100,
    longitude: 85.879500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2082-8082',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #82',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0083',
    facilityName: 'Odisha Blood Center #83 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0083',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.226100,
    longitude: 85.744500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2083-8083',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #83',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0084',
    facilityName: 'Odisha Blood Center #84 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0084',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.311100,
    longitude: 85.859500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2084-8084',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #84',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0085',
    facilityName: 'Odisha Blood Center #85 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0085',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.396100,
    longitude: 85.724500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2085-8085',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #85',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0086',
    facilityName: 'Odisha Blood Center #86 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0086',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.231100,
    longitude: 85.839500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2086-8086',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #86',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0087',
    facilityName: 'Odisha Blood Center #87 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0087',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.316100,
    longitude: 85.704500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2087-8087',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #87',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0088',
    facilityName: 'Odisha Blood Center #88 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0088',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.401100,
    longitude: 85.819500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2088-8088',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #88',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0089',
    facilityName: 'Odisha Blood Center #89 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0089',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.236100,
    longitude: 85.934500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2089-8089',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #89',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0090',
    facilityName: 'Odisha Blood Center #90 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0090',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.321100,
    longitude: 85.799500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2090-8090',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #90',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0091',
    facilityName: 'Odisha Blood Center #91 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0091',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.406100,
    longitude: 85.914500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2091-8091',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #91',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0092',
    facilityName: 'Odisha Blood Center #92 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0092',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.241100,
    longitude: 85.779500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2092-8092',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #92',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0093',
    facilityName: 'Odisha Blood Center #93 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0093',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.326100,
    longitude: 85.894500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2093-8093',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #93',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0094',
    facilityName: 'Odisha Blood Center #94 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0094',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.411100,
    longitude: 85.759500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2094-8094',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #94',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0095',
    facilityName: 'Odisha Blood Center #95 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0095',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.246100,
    longitude: 85.874500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2095-8095',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #95',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0096',
    facilityName: 'Odisha Blood Center #96 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0096',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.331100,
    longitude: 85.739500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2096-8096',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #96',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0097',
    facilityName: 'Odisha Blood Center #97 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0097',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.416100,
    longitude: 85.854500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2097-8097',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #97',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0098',
    facilityName: 'Odisha Blood Center #98 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0098',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.251100,
    longitude: 85.719500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2098-8098',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #98',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0099',
    facilityName: 'Odisha Blood Center #99 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0099',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.336100,
    longitude: 85.834500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2099-8099',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #99',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0100',
    facilityName: 'Odisha Blood Center #100 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0100',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.171100,
    longitude: 85.699500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2100-8100',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #100',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0101',
    facilityName: 'Odisha Blood Center #101 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0101',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.256100,
    longitude: 85.814500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2101-8101',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #101',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0102',
    facilityName: 'Odisha Blood Center #102 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0102',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.341100,
    longitude: 85.929500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2102-8102',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #102',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0103',
    facilityName: 'Odisha Blood Center #103 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0103',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.176100,
    longitude: 85.794500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2103-8103',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #103',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0104',
    facilityName: 'Odisha Blood Center #104 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0104',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.261100,
    longitude: 85.909500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2104-8104',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #104',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0105',
    facilityName: 'Odisha Blood Center #105 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0105',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.346100,
    longitude: 85.774500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2105-8105',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #105',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0106',
    facilityName: 'Odisha Blood Center #106 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0106',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.181100,
    longitude: 85.889500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2106-8106',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #106',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0107',
    facilityName: 'Odisha Blood Center #107 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0107',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.266100,
    longitude: 85.754500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2107-8107',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #107',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0108',
    facilityName: 'Odisha Blood Center #108 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2020/0108',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 20.351100,
    longitude: 85.869500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2108-8108',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #108',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-ODIS-0109',
    facilityName: 'Odisha Blood Center #109 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2021/0109',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 20.186100,
    longitude: 85.734500,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2109-8109',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #109',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-ODIS-0110',
    facilityName: 'Odisha Blood Center #110 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2022/0110',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 20.271100,
    longitude: 85.849500,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2110-8110',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #110',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-ODIS-0111',
    facilityName: 'Odisha Blood Center #111 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2023/0111',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 20.356100,
    longitude: 85.714500,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2111-8111',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #111',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-ODIS-0112',
    facilityName: 'Odisha Blood Center #112 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2024/0112',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 20.191100,
    longitude: 85.829500,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2112-8112',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #112',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-ODIS-0113',
    facilityName: 'Odisha Blood Center #113 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-ODI-2025/0113',
    stateRegion: 'Odisha — Bhubaneswar & Cuttack Twin Cities',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 20.276100,
    longitude: 85.944500,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2113-8113',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Odis #113',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
];

export function getOdishaBhubaneswarFacilityById(id: string): BloodBankFacilityRecord | undefined {
  return ODISHABHUBANESWAR_FACILITIES.find(f => f.id === id);
}

export function calculateHaversineDistanceKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371;
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a = Math.sin(dLat/2) * Math.sin(dLat/2) + Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLon/2) * Math.sin(dLon/2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
  return R * c;
}
