/**
 * BloodBridge Geo Registry — Tamil Nadu — Chennai Metropolitan Zone
 * Licensed blood banks, trauma centers, and cold chain distribution hubs.
 */

export interface BloodBankFacilityRecord {
  id: string;
  facilityName: string;
  licenseNumber: string;
  stateRegion: string;
  districtCity: string;
  latitude: number;
  longitude: number;
  category: 'GOVERNMENT_MEDICAL_COLLEGE' | 'RED_CROSS_REGIONAL' | 'PRIVATE_TERTIARY' | 'DEFENCE_MILITARY' | 'CHARITABLE_TRUST';
  componentSeparationLicensed: boolean;
  apheresisAvailable: boolean;
  natTestingAvailable: boolean;
  refrigeratedCentrifugeUnits: number;
  deepFreezersMinus80Count: number;
  plateletAgitatorsCount: number;
  averageMonthlyCollectionUnits: number;
  emergencyContactPhone: string;
  nodalTransfusionOfficer: string;
  operatingHours: string;
  greenCorridorDispatchEnabled: boolean;
  backupGeneratorCapacityKva: number;
}

export const TAMILNADUCHENNAI_FACILITIES: BloodBankFacilityRecord[] = [
  {
    id: 'FAC-TAMI-0001',
    facilityName: 'Tamil Nadu Blood Center #1 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0001',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.042700,
    longitude: 80.260700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2001-8001',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #1',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0002',
    facilityName: 'Tamil Nadu Blood Center #2 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0002',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.127700,
    longitude: 80.375700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2002-8002',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #2',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0003',
    facilityName: 'Tamil Nadu Blood Center #3 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0003',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.962700,
    longitude: 80.240700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2003-8003',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #3',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0004',
    facilityName: 'Tamil Nadu Blood Center #4 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0004',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.047700,
    longitude: 80.355700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2004-8004',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #4',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0005',
    facilityName: 'Tamil Nadu Blood Center #5 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0005',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.132700,
    longitude: 80.220700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2005-8005',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #5',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0006',
    facilityName: 'Tamil Nadu Blood Center #6 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0006',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.967700,
    longitude: 80.335700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2006-8006',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #6',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0007',
    facilityName: 'Tamil Nadu Blood Center #7 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0007',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.052700,
    longitude: 80.200700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2007-8007',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #7',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0008',
    facilityName: 'Tamil Nadu Blood Center #8 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0008',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.137700,
    longitude: 80.315700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2008-8008',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #8',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0009',
    facilityName: 'Tamil Nadu Blood Center #9 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0009',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.972700,
    longitude: 80.180700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2009-8009',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #9',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0010',
    facilityName: 'Tamil Nadu Blood Center #10 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0010',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.057700,
    longitude: 80.295700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2010-8010',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #10',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0011',
    facilityName: 'Tamil Nadu Blood Center #11 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0011',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.142700,
    longitude: 80.160700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2011-8011',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #11',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0012',
    facilityName: 'Tamil Nadu Blood Center #12 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0012',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.977700,
    longitude: 80.275700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2012-8012',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #12',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0013',
    facilityName: 'Tamil Nadu Blood Center #13 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0013',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.062700,
    longitude: 80.390700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2013-8013',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #13',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0014',
    facilityName: 'Tamil Nadu Blood Center #14 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0014',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.147700,
    longitude: 80.255700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2014-8014',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #14',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0015',
    facilityName: 'Tamil Nadu Blood Center #15 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0015',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.982700,
    longitude: 80.370700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2015-8015',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #15',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0016',
    facilityName: 'Tamil Nadu Blood Center #16 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0016',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.067700,
    longitude: 80.235700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2016-8016',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #16',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0017',
    facilityName: 'Tamil Nadu Blood Center #17 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0017',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.152700,
    longitude: 80.350700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2017-8017',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #17',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0018',
    facilityName: 'Tamil Nadu Blood Center #18 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0018',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.987700,
    longitude: 80.215700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2018-8018',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #18',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0019',
    facilityName: 'Tamil Nadu Blood Center #19 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0019',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.072700,
    longitude: 80.330700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2019-8019',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #19',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0020',
    facilityName: 'Tamil Nadu Blood Center #20 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0020',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.157700,
    longitude: 80.195700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2020-8020',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #20',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0021',
    facilityName: 'Tamil Nadu Blood Center #21 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0021',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 12.992700,
    longitude: 80.310700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2021-8021',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #21',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0022',
    facilityName: 'Tamil Nadu Blood Center #22 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0022',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.077700,
    longitude: 80.175700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2022-8022',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #22',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0023',
    facilityName: 'Tamil Nadu Blood Center #23 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0023',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.162700,
    longitude: 80.290700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2023-8023',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #23',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0024',
    facilityName: 'Tamil Nadu Blood Center #24 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0024',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 12.997700,
    longitude: 80.155700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2024-8024',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #24',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0025',
    facilityName: 'Tamil Nadu Blood Center #25 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0025',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.082700,
    longitude: 80.270700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2025-8025',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #25',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0026',
    facilityName: 'Tamil Nadu Blood Center #26 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0026',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.167700,
    longitude: 80.385700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2026-8026',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #26',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0027',
    facilityName: 'Tamil Nadu Blood Center #27 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0027',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.002700,
    longitude: 80.250700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2027-8027',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #27',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0028',
    facilityName: 'Tamil Nadu Blood Center #28 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0028',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.087700,
    longitude: 80.365700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2028-8028',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #28',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0029',
    facilityName: 'Tamil Nadu Blood Center #29 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0029',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.172700,
    longitude: 80.230700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2029-8029',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #29',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0030',
    facilityName: 'Tamil Nadu Blood Center #30 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0030',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.007700,
    longitude: 80.345700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2030-8030',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #30',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0031',
    facilityName: 'Tamil Nadu Blood Center #31 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0031',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.092700,
    longitude: 80.210700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2031-8031',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #31',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0032',
    facilityName: 'Tamil Nadu Blood Center #32 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0032',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.177700,
    longitude: 80.325700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2032-8032',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #32',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0033',
    facilityName: 'Tamil Nadu Blood Center #33 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0033',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.012700,
    longitude: 80.190700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2033-8033',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #33',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0034',
    facilityName: 'Tamil Nadu Blood Center #34 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0034',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.097700,
    longitude: 80.305700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2034-8034',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #34',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0035',
    facilityName: 'Tamil Nadu Blood Center #35 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0035',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.182700,
    longitude: 80.170700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2035-8035',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #35',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0036',
    facilityName: 'Tamil Nadu Blood Center #36 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0036',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.017700,
    longitude: 80.285700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2036-8036',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #36',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0037',
    facilityName: 'Tamil Nadu Blood Center #37 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0037',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.102700,
    longitude: 80.150700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2037-8037',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #37',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0038',
    facilityName: 'Tamil Nadu Blood Center #38 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0038',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.187700,
    longitude: 80.265700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2038-8038',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #38',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0039',
    facilityName: 'Tamil Nadu Blood Center #39 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0039',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.022700,
    longitude: 80.380700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2039-8039',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #39',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0040',
    facilityName: 'Tamil Nadu Blood Center #40 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0040',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.107700,
    longitude: 80.245700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2040-8040',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #40',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0041',
    facilityName: 'Tamil Nadu Blood Center #41 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0041',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.192700,
    longitude: 80.360700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2041-8041',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #41',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0042',
    facilityName: 'Tamil Nadu Blood Center #42 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0042',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.027700,
    longitude: 80.225700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2042-8042',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #42',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0043',
    facilityName: 'Tamil Nadu Blood Center #43 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0043',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.112700,
    longitude: 80.340700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2043-8043',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #43',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0044',
    facilityName: 'Tamil Nadu Blood Center #44 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0044',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.197700,
    longitude: 80.205700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2044-8044',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #44',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0045',
    facilityName: 'Tamil Nadu Blood Center #45 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0045',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.032700,
    longitude: 80.320700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2045-8045',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #45',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0046',
    facilityName: 'Tamil Nadu Blood Center #46 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0046',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.117700,
    longitude: 80.185700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2046-8046',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #46',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0047',
    facilityName: 'Tamil Nadu Blood Center #47 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0047',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.202700,
    longitude: 80.300700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2047-8047',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #47',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0048',
    facilityName: 'Tamil Nadu Blood Center #48 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0048',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.037700,
    longitude: 80.165700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2048-8048',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #48',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0049',
    facilityName: 'Tamil Nadu Blood Center #49 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0049',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.122700,
    longitude: 80.280700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2049-8049',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #49',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0050',
    facilityName: 'Tamil Nadu Blood Center #50 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0050',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.957700,
    longitude: 80.145700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2050-8050',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #50',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0051',
    facilityName: 'Tamil Nadu Blood Center #51 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0051',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.042700,
    longitude: 80.260700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2051-8051',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #51',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0052',
    facilityName: 'Tamil Nadu Blood Center #52 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0052',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.127700,
    longitude: 80.375700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2052-8052',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #52',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0053',
    facilityName: 'Tamil Nadu Blood Center #53 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0053',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 12.962700,
    longitude: 80.240700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2053-8053',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #53',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0054',
    facilityName: 'Tamil Nadu Blood Center #54 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0054',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.047700,
    longitude: 80.355700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2054-8054',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #54',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0055',
    facilityName: 'Tamil Nadu Blood Center #55 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0055',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.132700,
    longitude: 80.220700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2055-8055',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #55',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0056',
    facilityName: 'Tamil Nadu Blood Center #56 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0056',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.967700,
    longitude: 80.335700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2056-8056',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #56',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0057',
    facilityName: 'Tamil Nadu Blood Center #57 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0057',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.052700,
    longitude: 80.200700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2057-8057',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #57',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0058',
    facilityName: 'Tamil Nadu Blood Center #58 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0058',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.137700,
    longitude: 80.315700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2058-8058',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #58',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0059',
    facilityName: 'Tamil Nadu Blood Center #59 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0059',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 12.972700,
    longitude: 80.180700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2059-8059',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #59',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0060',
    facilityName: 'Tamil Nadu Blood Center #60 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0060',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.057700,
    longitude: 80.295700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2060-8060',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #60',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0061',
    facilityName: 'Tamil Nadu Blood Center #61 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0061',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.142700,
    longitude: 80.160700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2061-8061',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #61',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0062',
    facilityName: 'Tamil Nadu Blood Center #62 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0062',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.977700,
    longitude: 80.275700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2062-8062',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #62',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0063',
    facilityName: 'Tamil Nadu Blood Center #63 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0063',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.062700,
    longitude: 80.390700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2063-8063',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #63',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0064',
    facilityName: 'Tamil Nadu Blood Center #64 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0064',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.147700,
    longitude: 80.255700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2064-8064',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #64',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0065',
    facilityName: 'Tamil Nadu Blood Center #65 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0065',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 12.982700,
    longitude: 80.370700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2065-8065',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #65',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0066',
    facilityName: 'Tamil Nadu Blood Center #66 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0066',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.067700,
    longitude: 80.235700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2066-8066',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #66',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0067',
    facilityName: 'Tamil Nadu Blood Center #67 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0067',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.152700,
    longitude: 80.350700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2067-8067',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #67',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0068',
    facilityName: 'Tamil Nadu Blood Center #68 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0068',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.987700,
    longitude: 80.215700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2068-8068',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #68',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0069',
    facilityName: 'Tamil Nadu Blood Center #69 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0069',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.072700,
    longitude: 80.330700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2069-8069',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #69',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0070',
    facilityName: 'Tamil Nadu Blood Center #70 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0070',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.157700,
    longitude: 80.195700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2070-8070',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #70',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0071',
    facilityName: 'Tamil Nadu Blood Center #71 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0071',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 12.992700,
    longitude: 80.310700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2071-8071',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #71',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0072',
    facilityName: 'Tamil Nadu Blood Center #72 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0072',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.077700,
    longitude: 80.175700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2072-8072',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #72',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0073',
    facilityName: 'Tamil Nadu Blood Center #73 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0073',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.162700,
    longitude: 80.290700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2073-8073',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #73',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0074',
    facilityName: 'Tamil Nadu Blood Center #74 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0074',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 12.997700,
    longitude: 80.155700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2074-8074',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #74',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0075',
    facilityName: 'Tamil Nadu Blood Center #75 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0075',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.082700,
    longitude: 80.270700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2075-8075',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #75',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0076',
    facilityName: 'Tamil Nadu Blood Center #76 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0076',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.167700,
    longitude: 80.385700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2076-8076',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #76',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0077',
    facilityName: 'Tamil Nadu Blood Center #77 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0077',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.002700,
    longitude: 80.250700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2077-8077',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #77',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0078',
    facilityName: 'Tamil Nadu Blood Center #78 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0078',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.087700,
    longitude: 80.365700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2078-8078',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #78',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0079',
    facilityName: 'Tamil Nadu Blood Center #79 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0079',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.172700,
    longitude: 80.230700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2079-8079',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #79',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0080',
    facilityName: 'Tamil Nadu Blood Center #80 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0080',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.007700,
    longitude: 80.345700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2080-8080',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #80',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0081',
    facilityName: 'Tamil Nadu Blood Center #81 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0081',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.092700,
    longitude: 80.210700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2081-8081',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #81',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0082',
    facilityName: 'Tamil Nadu Blood Center #82 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0082',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.177700,
    longitude: 80.325700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2082-8082',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #82',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0083',
    facilityName: 'Tamil Nadu Blood Center #83 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0083',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.012700,
    longitude: 80.190700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2083-8083',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #83',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0084',
    facilityName: 'Tamil Nadu Blood Center #84 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0084',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.097700,
    longitude: 80.305700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2084-8084',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #84',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0085',
    facilityName: 'Tamil Nadu Blood Center #85 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0085',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.182700,
    longitude: 80.170700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2085-8085',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #85',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0086',
    facilityName: 'Tamil Nadu Blood Center #86 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0086',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.017700,
    longitude: 80.285700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2086-8086',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #86',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0087',
    facilityName: 'Tamil Nadu Blood Center #87 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0087',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.102700,
    longitude: 80.150700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2087-8087',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #87',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0088',
    facilityName: 'Tamil Nadu Blood Center #88 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0088',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.187700,
    longitude: 80.265700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2088-8088',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #88',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0089',
    facilityName: 'Tamil Nadu Blood Center #89 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0089',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.022700,
    longitude: 80.380700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2089-8089',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #89',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0090',
    facilityName: 'Tamil Nadu Blood Center #90 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0090',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.107700,
    longitude: 80.245700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2090-8090',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #90',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0091',
    facilityName: 'Tamil Nadu Blood Center #91 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0091',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.192700,
    longitude: 80.360700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2091-8091',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #91',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0092',
    facilityName: 'Tamil Nadu Blood Center #92 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0092',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.027700,
    longitude: 80.225700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2092-8092',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #92',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0093',
    facilityName: 'Tamil Nadu Blood Center #93 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0093',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.112700,
    longitude: 80.340700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2093-8093',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #93',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0094',
    facilityName: 'Tamil Nadu Blood Center #94 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0094',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 13.197700,
    longitude: 80.205700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2094-8094',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #94',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0095',
    facilityName: 'Tamil Nadu Blood Center #95 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0095',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.032700,
    longitude: 80.320700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2095-8095',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #95',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0096',
    facilityName: 'Tamil Nadu Blood Center #96 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0096',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.117700,
    longitude: 80.185700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2096-8096',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #96',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0097',
    facilityName: 'Tamil Nadu Blood Center #97 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0097',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 13.202700,
    longitude: 80.300700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2097-8097',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #97',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0098',
    facilityName: 'Tamil Nadu Blood Center #98 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0098',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.037700,
    longitude: 80.165700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2098-8098',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #98',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0099',
    facilityName: 'Tamil Nadu Blood Center #99 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0099',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.122700,
    longitude: 80.280700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 3300,
    emergencyContactPhone: '+91-11-2099-8099',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #99',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0100',
    facilityName: 'Tamil Nadu Blood Center #100 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0100',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 12.957700,
    longitude: 80.145700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 3500,
    emergencyContactPhone: '+91-11-2100-8100',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #100',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0101',
    facilityName: 'Tamil Nadu Blood Center #101 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0101',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.042700,
    longitude: 80.260700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 3700,
    emergencyContactPhone: '+91-11-2101-8101',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #101',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0102',
    facilityName: 'Tamil Nadu Blood Center #102 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0102',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.127700,
    longitude: 80.375700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 3900,
    emergencyContactPhone: '+91-11-2102-8102',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #102',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0103',
    facilityName: 'Tamil Nadu Blood Center #103 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0103',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 12.962700,
    longitude: 80.240700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 4100,
    emergencyContactPhone: '+91-11-2103-8103',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #103',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0104',
    facilityName: 'Tamil Nadu Blood Center #104 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0104',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.047700,
    longitude: 80.355700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 4300,
    emergencyContactPhone: '+91-11-2104-8104',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #104',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0105',
    facilityName: 'Tamil Nadu Blood Center #105 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0105',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.132700,
    longitude: 80.220700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 1500,
    emergencyContactPhone: '+91-11-2105-8105',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #105',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0106',
    facilityName: 'Tamil Nadu Blood Center #106 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0106',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 12.967700,
    longitude: 80.335700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 1700,
    emergencyContactPhone: '+91-11-2106-8106',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #106',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0107',
    facilityName: 'Tamil Nadu Blood Center #107 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0107',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.052700,
    longitude: 80.200700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 1900,
    emergencyContactPhone: '+91-11-2107-8107',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #107',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0108',
    facilityName: 'Tamil Nadu Blood Center #108 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2020/0108',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 6 Metropolitan Sector',
    latitude: 13.137700,
    longitude: 80.315700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 2100,
    emergencyContactPhone: '+91-11-2108-8108',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #108',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 275,
  },
  {
    id: 'FAC-TAMI-0109',
    facilityName: 'Tamil Nadu Blood Center #109 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2021/0109',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 1 Metropolitan Sector',
    latitude: 12.972700,
    longitude: 80.180700,
    category: 'CHARITABLE_TRUST',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 6,
    averageMonthlyCollectionUnits: 2300,
    emergencyContactPhone: '+91-11-2109-8109',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #109',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 325,
  },
  {
    id: 'FAC-TAMI-0110',
    facilityName: 'Tamil Nadu Blood Center #110 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2022/0110',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 2 Metropolitan Sector',
    latitude: 13.057700,
    longitude: 80.295700,
    category: 'GOVERNMENT_MEDICAL_COLLEGE',
    componentSeparationLicensed: false,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 4,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 2,
    averageMonthlyCollectionUnits: 2500,
    emergencyContactPhone: '+91-11-2110-8110',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #110',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 125,
  },
  {
    id: 'FAC-TAMI-0111',
    facilityName: 'Tamil Nadu Blood Center #111 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2023/0111',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 3 Metropolitan Sector',
    latitude: 13.142700,
    longitude: 80.160700,
    category: 'RED_CROSS_REGIONAL',
    componentSeparationLicensed: true,
    apheresisAvailable: false,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 5,
    deepFreezersMinus80Count: 1,
    plateletAgitatorsCount: 3,
    averageMonthlyCollectionUnits: 2700,
    emergencyContactPhone: '+91-11-2111-8111',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #111',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 175,
  },
  {
    id: 'FAC-TAMI-0112',
    facilityName: 'Tamil Nadu Blood Center #112 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2024/0112',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 4 Metropolitan Sector',
    latitude: 12.977700,
    longitude: 80.275700,
    category: 'PRIVATE_TERTIARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: true,
    refrigeratedCentrifugeUnits: 2,
    deepFreezersMinus80Count: 2,
    plateletAgitatorsCount: 4,
    averageMonthlyCollectionUnits: 2900,
    emergencyContactPhone: '+91-11-2112-8112',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #112',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: false,
    backupGeneratorCapacityKva: 225,
  },
  {
    id: 'FAC-TAMI-0113',
    facilityName: 'Tamil Nadu Blood Center #113 — Apex Hospital & Research Institute',
    licenseNumber: 'CDSCO/DL-TAM-2025/0113',
    stateRegion: 'Tamil Nadu — Chennai Metropolitan Zone',
    districtCity: 'Zone 5 Metropolitan Sector',
    latitude: 13.062700,
    longitude: 80.390700,
    category: 'DEFENCE_MILITARY',
    componentSeparationLicensed: true,
    apheresisAvailable: true,
    natTestingAvailable: false,
    refrigeratedCentrifugeUnits: 3,
    deepFreezersMinus80Count: 3,
    plateletAgitatorsCount: 5,
    averageMonthlyCollectionUnits: 3100,
    emergencyContactPhone: '+91-11-2113-8113',
    nodalTransfusionOfficer: 'Dr. Officer In-Charge Tami #113',
    operatingHours: '24x7 Emergency Transfusion & Component Issue',
    greenCorridorDispatchEnabled: true,
    backupGeneratorCapacityKva: 275,
  },
];

export function getTamilNaduChennaiFacilityById(id: string): BloodBankFacilityRecord | undefined {
  return TAMILNADUCHENNAI_FACILITIES.find(f => f.id === id);
}

export function calculateHaversineDistanceKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371;
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a = Math.sin(dLat/2) * Math.sin(dLat/2) + Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLon/2) * Math.sin(dLon/2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
  return R * c;
}
